"""T0420: closed, executable fixture for the OpenAPI derivation contract.

The corpus (tests/fixtures/openapi/cases.json, generated by
tools/openapi_fixture_generate.py) is a set of exact mutation lists over the
shipped control-plane source plus expectations authored from the structured
contract (data/contracts/openapi.yaml), never computed by the reference.
Every row executes against the T0419 test-only reference derive() as a
separate binding. Sections:

- happy: the baseline document shape, security, idempotency, schema and
  error-response rules, and additive field changes;
- boundary: major, name, route and example-magnitude ceilings, each as an
  accepted edge and a refused step past it;
- malformed: source shape, grammar, cross-reference, example, write-only and
  chess-token violations refuse typed;
- rollback: refusals leave the source bit-identical, return no document and
  disturb nothing: the shipped source still derives the pinned golden bytes.

Every row also runs the shared invariants (source unchanged, typed fresh
refusal, deterministic canonical bytes, detached document). The mutant
battery wraps derive with one-edit behavioral defects; every kill is a
failed fixture row, never a crash or a source-text check.
"""

from __future__ import annotations

import copy
import hashlib
import json
import sys
from pathlib import Path

import pytest
import yaml

import tests.test_t0419_openapi_contract as _REF
import tools.openapi_fixture_generate as _GEN

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "openapi" / "cases.json"
CASES = json.loads(FIXTURE.read_text())
SOURCE_PATH = ROOT / CASES["source"]
SECTIONS = ("happy", "boundary", "malformed", "rollback")
TOP_KEYS = {
    "schema_version",
    "contract",
    "contract_schema_version",
    "source",
    "notes",
    "source_manifest",
    "section_manifests",
    *SECTIONS,
}
ROW_KEYS = {"name", "why", "mutations", "expect"}
ACTIONS = {
    "set": {"path", "value"},
    "del": {"path"},
    "append": {"path", "value"},
    "replace_root": {"value"},
}
FAILURE = "malformed_control_plane"
CODE = "malformed_request"


def _derive(source):
    """Late-bound so the mutant battery can rebind the reference."""
    return _REF.derive(source)


def _canon(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


_SHIPPED_TEXT = SOURCE_PATH.read_text()
_SHIPPED_DOC = yaml.safe_load(_SHIPPED_TEXT)


def _shipped():
    return copy.deepcopy(_SHIPPED_DOC)


# -- mutation materialization ---------------------------------------------------


class FixtureError(Exception):
    """A corpus row that cannot be materialized against the shipped source."""


def _resolve(doc, path, where):
    node = doc
    for key in path[:-1]:
        if type(node) is not dict or key not in node:
            raise FixtureError(f"{where}: unresolvable path {path}")
        node = node[key]
    if type(node) is not dict:
        raise FixtureError(f"{where}: unresolvable path {path}")
    return node, path[-1]


def _materialize(mutations, where):
    doc = _shipped()
    for mutation in mutations:
        assert type(mutation) is dict and len(mutation) == 1, where
        (action,) = mutation
        spec = mutation[action]
        assert action in ACTIONS and set(spec) == ACTIONS[action], where
        if action == "replace_root":
            doc = copy.deepcopy(spec["value"])
            continue
        path = spec["path"]
        assert type(path) is list and path and all(type(k) is str for k in path), where
        node, last = _resolve(doc, path, where)
        if action == "set":
            node[last] = copy.deepcopy(spec["value"])
        elif action == "del":
            if last not in node:
                raise FixtureError(f"{where}: del of missing key {path}")
            del node[last]
        else:
            if type(node.get(last)) is not list:
                raise FixtureError(f"{where}: append to non-list {path}")
            node[last].append(copy.deepcopy(spec["value"]))
    return doc


# -- closed-corpus structure ------------------------------------------------------


def _check_expect(expect, where):
    assert type(expect) is dict, where
    if expect == {"kind": "refusal"}:
        return
    assert set(expect) == {"kind", "checks"} and expect["kind"] == "document", where
    assert type(expect["checks"]) is list and expect["checks"], where
    for check in expect["checks"]:
        assert type(check) is dict and type(check["at"]) is list, where
        assert all(type(k) in (str, int) for k in check["at"]), where
        kind = set(check) - {"at"}
        assert kind in ({"equals"}, {"absent"}, {"keys"}), where
        if "absent" in check:
            assert check["absent"] is True, where
        if "keys" in check:
            assert type(check["keys"]) is list, where


def _check_row(row, where):
    assert type(row) is dict, where
    assert set(row) - {"then_baseline"} == ROW_KEYS, where
    assert type(row["name"]) is str and row["name"], where
    assert type(row["why"]) is str and row["why"], where
    assert type(row["mutations"]) is list, where
    if "then_baseline" in row:
        assert row["then_baseline"] is True, where
    _check_expect(row["expect"], where)
    _materialize(row["mutations"], where)


def _check(cases):
    assert type(cases) is dict and set(cases) == TOP_KEYS, sorted(cases)
    assert cases["schema_version"] == 1
    assert cases["contract"] == "data/contracts/openapi.yaml"
    assert cases["source"] == "data/contracts/control-plane.yaml"
    assert "separate binding" in cases["notes"]
    contract = yaml.safe_load((ROOT / cases["contract"]).read_text())
    assert cases["contract_schema_version"] == contract["schema_version"]
    assert hashlib.sha256(_canon(_shipped())).hexdigest() == cases["source_manifest"]
    assert set(cases["section_manifests"]) == set(SECTIONS)
    names = []
    for section in SECTIONS:
        rows = cases[section]
        assert type(rows) is list and rows, section
        manifest = cases["section_manifests"][section]
        assert list(manifest) == [r["name"] for r in rows], section
        for row in rows:
            _check_row(row, f"{section}:{row.get('name')}")
            assert manifest[row["name"]] == hashlib.sha256(_canon(row)).hexdigest()
        names.extend(r["name"] for r in rows)
    assert len(names) == len(set(names))


def test_corpus_is_closed_and_every_row_materializes():
    _check(CASES)


def test_corpus_is_exactly_what_the_generator_writes():
    assert _GEN.build() == CASES


def test_manifest_is_bound_to_row_bytes():
    cases = copy.deepcopy(CASES)
    cases["malformed"][0]["why"] += " edited"
    with pytest.raises(AssertionError):
        _check(cases)


def test_manifest_is_bound_to_the_shipped_source(monkeypatch):
    shipped = copy.deepcopy(_SHIPPED_DOC)
    shipped["areas"]["identity"]["ops"]["register"]["errors"].append("conflict")
    monkeypatch.setattr(sys.modules[__name__], "_SHIPPED_DOC", shipped)
    with pytest.raises(AssertionError):
        _check(CASES)


def test_every_section_is_populated_and_covers_the_listed_behaviors():
    counts = {s: len(CASES[s]) for s in SECTIONS}
    assert all(n >= 3 for n in counts.values()), counts
    refused = [r for s in SECTIONS for r in CASES[s] if r["expect"]["kind"] == "refusal"]
    accepted = [r for s in SECTIONS for r in CASES[s] if r["expect"]["kind"] == "document"]
    assert len(refused) >= 30 and len(accepted) >= 15
    assert all(r["expect"]["kind"] == "refusal" for r in CASES["malformed"])


# -- expectation evaluation -------------------------------------------------------

_MISSING = object()


def _at(document, path):
    node = document
    for key in path:
        if (
            type(node) is dict
            and key in node
            or type(node) is list
            and type(key) is int
            and -len(node) <= key < len(node)
        ):
            node = node[key]
        else:
            return _MISSING
    return node


def _failures_of_check(document, check):
    value = _at(document, check["at"])
    where = "/".join(str(k) for k in check["at"])
    if "equals" in check:
        if value != check["equals"] or type(value) is not type(check["equals"]):
            return [f"{where}: expected {check['equals']!r}"]
    elif "absent" in check:
        if value is not _MISSING:
            return [f"{where}: expected absent"]
    elif (
        type(value) not in (dict, list)
        or ([*value] if type(value) is dict else value) != check["keys"]
    ):
        return [f"{where}: expected keys {check['keys']!r}"]
    return []


def _containers(value, out):
    stack = [value]
    while stack:
        node = stack.pop()
        if type(node) is dict:
            out.add(id(node))
            stack.extend(node.values())
        elif type(node) is list:
            out.add(id(node))
            stack.extend(node)
    return out


def _outcome(source):
    """('document', doc) or ('refusal', error) with the shared invariants."""
    before = copy.deepcopy(source)
    problems = []
    try:
        document = _derive(source)
    except _REF.OpenApiError as error:
        if (error.failure_class, error.code, error.retryable) != (FAILURE, CODE, False):
            problems.append(f"refusal shape {error.failure_class}/{error.code}")
        if error.__cause__ is not None or error.__context__ is not None:
            problems.append("refusal carries a cause or context")
        outcome = ("refusal", None)
    else:
        outcome = ("document", document)
        bytes_one = _REF.canonical_bytes(document)
        json.loads(bytes_one)
        if _REF.canonical_bytes(_derive(copy.deepcopy(before))) != bytes_one:
            problems.append("derivation is not deterministic")
        if _containers(document, set()) & _containers(source, set()):
            problems.append("document shares a container with the source")
    if source != before:
        problems.append("source was changed")
    return outcome, problems


def _run_row(row):
    """The list of semantic failures for one row; empty means the row holds."""
    source = _materialize(row["mutations"], row["name"])
    (kind, document), problems = _outcome(source)
    failures = list(problems)
    expect = row["expect"]
    if expect["kind"] == "refusal":
        if kind != "refusal":
            failures.append("derivation accepted a malformed source")
    elif kind != "document":
        failures.append("derivation refused a valid source")
    else:
        for check in expect["checks"]:
            failures.extend(_failures_of_check(document, check))
    if row.get("then_baseline"):
        (base_kind, base), base_problems = _outcome(_shipped())
        failures.extend(base_problems)
        if base_kind != "document" or _digest(base) != GOLDEN:
            failures.append("baseline after the row is not the golden document")
    return failures


def _digest(document):
    return hashlib.sha256(_REF.canonical_bytes(document)).hexdigest()


GOLDEN = _REF.GOLDEN_SHA256
ROWS = [(s, r) for s in SECTIONS for r in CASES[s]]


def test_golden_digest_is_the_pinned_t0419_baseline():
    (kind, document), problems = _outcome(_shipped())
    assert (kind, problems) == ("document", [])
    assert _digest(document) == GOLDEN
    assert len(_REF.canonical_bytes(document)) == _REF.GOLDEN_LENGTH


@pytest.mark.parametrize("section,row", ROWS, ids=[f"{s}:{r['name']}" for s, r in ROWS])
def test_row_holds_against_the_reference(section, row):
    assert _run_row(row) == []


# -- mutant battery: behavioral one-edit defects of derive ------------------------


def _post(transform):
    def mutate(derive):
        def mutant(source):
            document = derive(source)
            transform(document)
            return document

        return mutant

    return mutate


def _drop_idempotency(document):
    for item in document["paths"].values():
        for operation in item.values():
            operation["parameters"] = []


def _public_gets_bearer(document):
    document["paths"]["/identity/register"]["post"]["security"] = [{"bearerAuth": []}]


def _bearer_dropped(document):
    document["paths"]["/identity/refresh"]["post"]["security"] = []


def _sort_properties(document):
    schema = document["paths"]["/identity/register"]["post"]["requestBody"]["content"][
        "application/json"
    ]["schema"]
    schema["properties"] = dict(sorted(schema["properties"].items()))


def _optional_is_required(document):
    schema = document["paths"]["/identity/register"]["post"]["requestBody"]["content"][
        "application/json"
    ]["schema"]
    schema["required"] = list(schema["properties"])


def _invent_status(document):
    for item in document["paths"].values():
        for operation in item.values():
            if operation["operationId"] == "identity.login":
                operation["responses"]["429"] = {"description": "error"}


def _sort_paths(document):
    document["paths"] = dict(sorted(document["paths"].items()))


def _wrong_info_version(document):
    document["info"]["version"] = document["info"]["version"] + ".0.0"


def _wrong_server(document):
    document["servers"] = [{"url": "/"}]


def _lose_unmapped(document):
    document["x-unmapped-error-codes"] = []


def _status_group(document):
    responses = document["paths"]["/identity/refresh"]["post"]["responses"]
    if "401" in responses:
        responses["401"]["x-error-codes"] = ["auth_invalid", "auth_expired"]


def _public_is_listed_only(derive):
    """Accepts a source whose public list omits a public operation."""

    def mutant(source):
        try:
            return derive(source)
        except _REF.OpenApiError:
            if type(source) is not dict:
                raise
            patched = copy.deepcopy(source)
            patched["contract"]["transport"]["auth"]["public_operations"] = [
                "identity.register",
                "identity.login",
            ]
            return derive(patched)

    return mutant


def _lax_base_path(derive):
    def mutant(source):
        try:
            return derive(source)
        except _REF.OpenApiError:
            if type(source) is not dict:
                raise
            patched = copy.deepcopy(source)
            patched["contract"]["versioning"]["base_path"] = "/cp/v1"
            return derive(patched)

    return mutant


def _swallow_refusals(derive):
    def mutant(source):
        try:
            return derive(source)
        except _REF.OpenApiError:
            return {"openapi": "3.1.0"}

    return mutant


def _mutates_source(derive):
    def mutant(source):
        document = derive(source)
        source["areas"]["identity"]["ops"]["register"]["errors"].sort()
        return document

    return mutant


def _shares_containers(derive):
    def mutant(source):
        document = derive(source)
        document["x-unmapped-error-codes"] = source["contract"]["transport"]["read_only_operations"]
        return document

    return mutant


def _nondeterministic(derive):
    calls = []

    def mutant(source):
        document = derive(source)
        calls.append(1)
        if len(calls) % 2 == 0:
            document["info"]["title"] += "!"
        return document

    return mutant


def _typed_refusal_carries_context(derive):
    def mutant(source):
        try:
            return derive(source)
        except _REF.OpenApiError as error:
            raise _REF.OpenApiError(error.failure_class, error.code, str(error)) from error

    return mutant


def _retryable_refusal(derive):
    def mutant(source):
        try:
            return derive(source)
        except _REF.OpenApiError:
            error = _REF.OpenApiError(FAILURE, CODE, "malformed")
            error.retryable = True
            raise error from None

    return mutant


def _wrong_refusal_code(derive):
    def mutant(source):
        try:
            return derive(source)
        except _REF.OpenApiError:
            raise _REF.OpenApiError(FAILURE, "internal", "malformed") from None

    return mutant


def _stateful_after_refusal(derive):
    state = {"refused": False}

    def mutant(source):
        try:
            document = derive(source)
        except _REF.OpenApiError:
            state["refused"] = True
            raise
        if state["refused"]:
            document["info"]["version"] = "0"
        return document

    return mutant


MUTANTS = {
    "drop-idempotency-parameters": _post(_drop_idempotency),
    "public-op-gets-bearer": _post(_public_gets_bearer),
    "bearer-op-loses-security": _post(_bearer_dropped),
    "sorted-properties": _post(_sort_properties),
    "optional-listed-required": _post(_optional_is_required),
    "invented-unmapped-status": _post(_invent_status),
    "sorted-paths": _post(_sort_paths),
    "dotted-info-version": _post(_wrong_info_version),
    "wrong-server-url": _post(_wrong_server),
    "lost-unmapped-codes": _post(_lose_unmapped),
    "swapped-status-code-order": _post(_status_group),
    "lax-public-list": _public_is_listed_only,
    "lax-base-path": _lax_base_path,
    "swallowed-refusals": _swallow_refusals,
    "mutates-source": _mutates_source,
    "shares-containers": _shares_containers,
    "nondeterministic": _nondeterministic,
    "refusal-chains-a-cause": _typed_refusal_carries_context,
    "retryable-refusal": _retryable_refusal,
    "wrong-refusal-code": _wrong_refusal_code,
    "stateful-after-refusal": _stateful_after_refusal,
}


def _killing_rows(label, monkeypatch):
    original = _REF.derive
    mutated = MUTANTS[label](original)
    monkeypatch.setattr(_REF, "derive", mutated)
    return [name for _, row in ROWS for name in [row["name"]] if _run_row(row)]


def test_unmutated_reference_fails_no_row():
    assert [row["name"] for _, row in ROWS if _run_row(row)] == []


@pytest.mark.parametrize("label", sorted(MUTANTS))
def test_mutant_is_killed_by_a_failed_row(label, monkeypatch):
    killed = _killing_rows(label, monkeypatch)
    assert killed, f"mutant {label} survived every fixture row"


def test_non_ascii_example_bytes_are_written_as_utf8_not_escaped():
    row = next(r for r in CASES["boundary"] if r["name"] == "example-non-ascii-string")
    (kind, document), problems = _outcome(_materialize(row["mutations"], row["name"]))
    assert (kind, problems) == ("document", [])
    data = _REF.canonical_bytes(document)
    assert "caf\u00e9 \u2603".encode() in data
    assert b"\\u00e9" not in data
