"""T0438: closed, executable fixture for the v1 control-plane versioning
contract.

The corpus (tests/fixtures/control-plane-versioning/cases.json, generated by
tools/versioning_fixture_generate.py) pins the base snapshot once plus exact
mutation lists that materialize each row's old/new snapshots, and executes
every row against the T0437 test-only reference compare() as a separate
binding. Expectations are authored from the structured contract
(data/contracts/control_plane_versioning.yaml), never computed by the
reference. The mutant battery's kills all come from executed fixture rows,
never source-text checks; the T0437 equivalent edits, preempted by strict
T0419 source validation, must keep the fixture green.
"""

from __future__ import annotations

import ast
import copy
import hashlib
import inspect
import json
from pathlib import Path

import pytest
import yaml

import tests.test_t0437_control_plane_versioning_contract as _REF
import tools.versioning_fixture_generate as _GEN

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "control-plane-versioning" / "cases.json"
CASES = json.loads(FIXTURE.read_text())
CONTRACT_DOC = yaml.safe_load((ROOT / CASES["contract"]).read_text())
SECTIONS = ("happy", "boundary", "incompatible", "malformed")
VERDICT_SECTIONS = ("happy", "boundary", "incompatible")
TOP_KEYS = {
    "schema_version",
    "contract",
    "contract_schema_version",
    "source",
    "notes",
    "base_snapshot",
    "base_manifest",
    "section_manifests",
    *SECTIONS,
}
ROW_KEYS = {"name", "why", "old", "new", "old_minor", "new_minor", "expect"}
FAILURE = "malformed_version_request"
CEILING = 2147483647
ACTIONS = {
    "set": {"path", "value"},
    "del": {"path"},
    "append": {"path", "value"},
    "remove": {"path", "value"},
    "extend": {"path", "values"},
    "reverse": {"path"},
}


def _compare(old, new, old_minor, new_minor):
    """Late-bound access so mutant batteries can rebind the reference."""
    return _REF.compare(old, new, old_minor, new_minor)


# -- mutation materialization ---------------------------------------------------


class FixtureError(Exception):
    """A corpus row that cannot be materialized or refuses its own shape."""


def _walk(doc, path, where):
    node = doc
    for key in path[:-1]:
        if type(node) is not dict or type(key) is not str or key not in node:
            raise FixtureError(f"{where}: unresolvable path {path}")
        node = node[key]
    if type(node) is not dict or type(path[-1]) is not str:
        raise FixtureError(f"{where}: unresolvable path {path}")
    return node, path[-1]


def _apply(doc, mutations, where):
    for mutation in mutations:
        if type(mutation) is not dict or len(mutation) != 1:
            raise FixtureError(f"{where}: malformed mutation {mutation}")
        (action,) = mutation
        if action not in ACTIONS or set(mutation[action]) != ACTIONS[action]:
            raise FixtureError(f"{where}: malformed mutation {mutation}")
        spec = mutation[action]
        path = spec["path"]
        if type(path) is not list or not path or not all(type(key) is str for key in path):
            raise FixtureError(f"{where}: malformed path {path}")
        node, last = _walk(doc, path, where)
        if action == "set":
            node[last] = copy.deepcopy(spec["value"])
        elif action == "del":
            if last not in node:
                raise FixtureError(f"{where}: del of missing key {path}")
            del node[last]
        else:
            target = node.get(last)
            if type(target) is not list:
                raise FixtureError(f"{where}: list action on non-list {path}")
            if action == "append":
                target.append(copy.deepcopy(spec["value"]))
            elif action == "remove":
                if spec["value"] not in target:
                    raise FixtureError(f"{where}: remove of absent value {path}")
                target.remove(spec["value"])
            elif action == "extend":
                values = spec["values"]
                if type(values) is not list:
                    raise FixtureError(f"{where}: extend of non-list {path}")
                target.extend(copy.deepcopy(values))
            else:
                target.reverse()


def _materialize(descriptor, where):
    doc = copy.deepcopy(CASES["base_snapshot"])
    _apply(doc, descriptor, where)
    return doc


def _snapshots(row):
    where = f"row:{row['name']}"
    return (
        _materialize(row["old"], f"{where}:old"),
        _materialize(row["new"], f"{where}:new"),
    )


# -- closed-corpus structure ------------------------------------------------------


def _canon(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def _check_mutation_lists(row, where):
    for side in ("old", "new"):
        mutations = row[side]
        assert type(mutations) is list, where
        for mutation in mutations:
            assert type(mutation) is dict and len(mutation) == 1, where
            (action,) = mutation
            assert action in ACTIONS, where
            assert set(mutation[action]) == ACTIONS[action], where
            path = mutation[action]["path"]
            assert type(path) is list and path, where
            assert all(type(key) is str for key in path), where
        # every mutation must materialize against the pinned base snapshot
        _materialize(mutations, f"{where}:{side}")


def _check_row(row, section, where):
    assert type(row) is dict and set(row) == ROW_KEYS, where
    assert type(row["name"]) is str and row["name"], where
    assert type(row["why"]) is str and row["why"], where
    _check_mutation_lists(row, where)
    if section == "malformed":
        assert row["expect"] == FAILURE, where
    else:
        assert type(row["expect"]) is bool, where
        for key in ("old_minor", "new_minor"):
            minor = row[key]
            assert type(minor) is int and 0 <= minor <= CEILING, where


def _check_section(cases, section):
    """The manifest closure for one section: digests, order, key shapes."""
    rows = cases[section]
    assert type(rows) is list and rows, section
    manifest = cases["section_manifests"][section]
    assert list(manifest) == [row["name"] for row in rows], section
    computed = {row["name"]: hashlib.sha256(_canon(row)).hexdigest() for row in rows}
    assert manifest == computed, section
    for row in rows:
        _check_row(row, section, f"{section}:{row.get('name')}")


def _check(cases):
    assert type(cases) is dict
    assert set(cases) == TOP_KEYS, f"top keys {sorted(cases)}"
    assert type(cases["schema_version"]) is int and cases["schema_version"] == 1
    assert cases["contract"] == "data/contracts/control_plane_versioning.yaml"
    assert cases["contract_schema_version"] == CONTRACT_DOC["schema_version"]
    assert cases["source"] == "data/contracts/control-plane.yaml"
    assert type(cases["notes"]) is str and "separate binding" in cases["notes"]
    base = cases["base_snapshot"]
    assert type(base) is dict and set(base) == {"schema_version", "contract", "areas"}
    assert hashlib.sha256(_canon(base)).hexdigest() == cases["base_manifest"]
    assert set(cases["section_manifests"]) == set(SECTIONS)
    names = []
    for section in SECTIONS:
        _check_section(cases, section)
        names.extend(row["name"] for row in cases[section])
    assert len(names) == len(set(names))


def test_fixture_structure():
    _check(CASES)


def test_fixture_matches_generator():
    assert _GEN.dump(_GEN.build()) == FIXTURE.read_text()


@pytest.mark.parametrize("section", SECTIONS)
def test_closed_manifest_detects_reorder_drop_and_extra(section):
    manifest = CASES["section_manifests"][section]
    names = [row["name"] for row in CASES[section]]
    assert list(manifest) == names
    assert len(names) == len(set(names))
    for mutant_rows in (
        list(reversed(CASES[section])),
        CASES[section][1:],
        [*CASES[section], copy.deepcopy(CASES[section][0])],
    ):
        mutant = copy.deepcopy(CASES)
        mutant[section] = mutant_rows
        with pytest.raises(AssertionError):
            _check_section(mutant, section)


def test_row_substitution_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                mutant_rows = copy.deepcopy(rows)
                replacement = copy.deepcopy(mutant_rows[donor])
                replacement["name"] = mutant_rows[target]["name"]
                mutant_rows[target] = replacement
                mutant = {**CASES, section: mutant_rows}
                with pytest.raises(AssertionError):
                    _check_section(mutant, section)


def test_each_row_field_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                shared = (set(rows[target]) & set(rows[donor])) - {"name"}
                for field in shared:
                    if rows[target][field] == rows[donor][field]:
                        continue
                    mutant_rows = copy.deepcopy(rows)
                    mutant_rows[target][field] = copy.deepcopy(rows[donor][field])
                    mutant = {**CASES, section: mutant_rows}
                    with pytest.raises(AssertionError):
                        _check_section(mutant, section)


def test_structure_mutations_fail():
    for bad in (True, 1.0, "1", 0, 2):
        mutant = copy.deepcopy(CASES)
        mutant["schema_version"] = bad
        with pytest.raises(AssertionError):
            _check(mutant)
    for section in SECTIONS:
        mutant = copy.deepcopy(CASES)
        mutant[section][0]["rogue"] = None
        with pytest.raises(AssertionError):
            _check(mutant)
        mutant = copy.deepcopy(CASES)
        mutant[section][0]["new"].append({"teleport": {"path": ["areas"]}})
        with pytest.raises(AssertionError):
            _check(mutant)
    mutant = copy.deepcopy(CASES)
    mutant["rogue_section"] = []
    with pytest.raises(AssertionError):
        _check(mutant)
    mutant = copy.deepcopy(CASES)
    mutant["base_snapshot"]["areas"]["identity"]["ops"]["register"]["path"] = "/identity/join"
    with pytest.raises(AssertionError):
        _check(mutant)


def test_unresolvable_mutation_paths_refuse():
    for descriptor in (
        [{"set": {"path": ["areas", "no_such_area", "ops"], "value": {}}}],
        [{"del": {"path": ["areas", "identity", "ops", "no_such_op"]}}],
        [{"append": {"path": ["areas", "identity", "ops", "register", "path"], "value": "x"}}],
        [{"remove": {"path": ["contract", "transport", "read_only_operations"], "value": "none"}}],
    ):
        with pytest.raises(FixtureError):
            _materialize(descriptor, "probe")


# -- executed rows --------------------------------------------------------------


def _run_verdict_row(row):
    old, new = _snapshots(row)
    before = copy.deepcopy((old, new))
    first = _compare(old, new, row["old_minor"], row["new_minor"])
    second = _compare(old, new, row["old_minor"], row["new_minor"])
    assert first is row["expect"], row["name"]
    assert second is row["expect"], row["name"]
    assert (old, new) == before, row["name"]


def _run_malformed_row(row):
    old, new = _snapshots(row)
    before = copy.deepcopy((old, new))
    errors = []
    for _ in range(2):
        with pytest.raises(_REF.VersionError) as caught:
            _compare(old, new, row["old_minor"], row["new_minor"])
        errors.append(caught.value)
    assert errors[0] is not errors[1], row["name"]
    for error in errors:
        assert error.failure_class == FAILURE, row["name"]
        assert error.code == "malformed_request", row["name"]
        assert error.retryable is False, row["name"]
        assert error.__cause__ is None and error.__context__ is None, row["name"]
    assert (old, new) == before, row["name"]


def _section_names(section):
    return [row["name"] for row in CASES[section]]


def _verdict_row(section, name):
    return next(row for row in CASES[section] if row["name"] == name)


@pytest.mark.parametrize(
    "section,name",
    [(section, name) for section in VERDICT_SECTIONS for name in _section_names(section)],
    ids=lambda value: value if value in SECTIONS else None,
)
def test_verdict_rows_execute_with_purity_and_determinism(section, name):
    _run_verdict_row(_verdict_row(section, name))


@pytest.mark.parametrize("name", _section_names("malformed"))
def test_malformed_rows_refuse_typed_with_purity(name):
    _run_malformed_row(_verdict_row("malformed", name))


# -- coverage pins ----------------------------------------------------------------


def test_happy_section_covers_every_minor_allowlist_class():
    names = set(_section_names("happy"))
    assert {
        "optional-request-field-added",
        "optional-response-field-added",
        "nested-optional-request-field-added",
        "nested-optional-response-field-added",
        "new-readonly-operation-with-allowlist",
        "new-public-operation-with-allowlist",
        "new-area-with-operation-and-allowlist",
    } <= names


def test_boundary_rows_cover_minor_ceiling_and_major_reset():
    boundary = CASES["boundary"]
    assert any(row["new_minor"] == CEILING for row in boundary)
    assert any(row["old_minor"] == CEILING for row in boundary)
    assert any(row["new"] and row["old_minor"] > row["new_minor"] for row in boundary), (
        "a MAJOR transition with a minor reset must be pinned"
    )


def test_malformed_rows_cover_minor_hostility_and_precedence():
    names = set(_section_names("malformed"))
    assert {
        "old-minor-over-ceiling",
        "new-minor-over-ceiling",
        "old-minor-bool",
        "new-minor-float",
        "old-minor-string",
        "new-minor-null",
        "minor-downgrade-same-major",
        "major-downgrade",
        "precedence-minor-bound-beats-comparison",
        "hostile-old-snapshot",
    } <= names


# -- mutant battery ---------------------------------------------------------------

REFERENCE_EDITS = dict(_REF.REFERENCE_MUTANTS)
EQUIVALENT_EDITS = dict(_REF.EQUIVALENT)


def _equivalent_compare(name):
    before, replacement, _probe = EQUIVALENT_EDITS[name]
    source = (
        inspect.getsource(_REF._fields)
        + "\n"
        + inspect.getsource(_REF._minor)
        + "\n"
        + inspect.getsource(_REF.compare)
    )
    assert source.count(before) == 1, name
    scope = dict(vars(_REF))
    exec(  # noqa: S102
        compile(ast.parse(source.replace(before, replacement, 1)), f"<equivalent:{name}>", "exec"),
        scope,
    )
    return scope["compare"]


def _fixture_red():
    """Labels of executed fixture rows that disagree with the reference
    currently bound; empty when green. Every label comes from a row executed
    through compare(): no source-text or table-shape check counts."""
    red = []
    for section in VERDICT_SECTIONS:
        for row in CASES[section]:
            try:
                _run_verdict_row(row)
            except BaseException:  # noqa: BLE001
                red.append(f"{section}:{row['name']}")
    for row in CASES["malformed"]:
        try:
            _run_malformed_row(row)
        except BaseException:  # noqa: BLE001
            red.append(f"malformed:{row['name']}")
    return red


def test_reference_edits_apply():
    for name in REFERENCE_EDITS:
        _REF._mutant_compare(name)
    for name in EQUIVALENT_EDITS:
        _equivalent_compare(name)


def test_reference_is_green():
    assert _fixture_red() == []


@pytest.mark.parametrize("name", sorted(REFERENCE_EDITS))
def test_reference_mutants_turn_the_fixture_red(name, monkeypatch):
    monkeypatch.setattr(_REF, "compare", _REF._mutant_compare(name))
    assert _fixture_red() != [], name


@pytest.mark.parametrize("name", sorted(EQUIVALENT_EDITS))
def test_equivalent_edits_keep_the_fixture_green(name, monkeypatch):
    monkeypatch.setattr(_REF, "compare", _equivalent_compare(name))
    assert _fixture_red() == [], name
