# ruff: noqa: E501  (exact contract literals and FEN/token-run probes)
"""T0447: closed, executable fixture for the v1 control-plane errors contract.

The corpus (tests/fixtures/control-plane-errors/cases.json, generated by
tools/control_plane_errors_fixture_generate.py) pins happy, boundary,
malformed and rollback rows for the pure HTTP error-payload classifier
declared in data/contracts/control_plane_errors.yaml and executes every row
against the T0446 test-only reference classify() as a separate binding; a
later implement task (T0449) must independently implement the classifier and
rebind these rows. Expectations are authored from the structured contract,
never computed by the reference. Python-level hostiles that JSON cannot
represent (lone surrogates, non-string keys, NaN/infinity, built-in
subclasses, plain objects) are derived in code from pinned rows; the mutant
battery's kills all come from executed fixture checks, never source-text
checks.
"""

from __future__ import annotations

import ast
import copy
import hashlib
import inspect
import json
import time
from pathlib import Path

import pytest
import yaml

import tests.test_t0446_control_plane_errors_contract as _REF
import tools.control_plane_errors_fixture_generate as _GEN

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "control-plane-errors" / "cases.json"
CASES = json.loads(FIXTURE.read_text())
SOURCE_DOC = yaml.safe_load((ROOT / CASES["source"]).read_text())
CONTRACT_DOC = yaml.safe_load((ROOT / CASES["contract"]).read_text())
ENUM = list(SOURCE_DOC["contract"]["transport"]["errors"]["closed_enum"])
OPERATIONS = {
    f"{area}.{op}" for area, detail in SOURCE_DOC["areas"].items() for op in detail["ops"]
}
FAILURE = "malformed_error_result"
FAILURE_CLASSES = set(CONTRACT_DOC["contract"]["failures"]["classes"])
SECTIONS = ("happy", "boundary", "malformed", "rollback")
VERDICT_SECTIONS = ("happy", "boundary")
TOP_KEYS = {
    "schema_version",
    "contract",
    "contract_schema_version",
    "source",
    "source_manifest",
    "notes",
    "section_manifests",
    *SECTIONS,
}
VERDICT_KEYS = {"name", "why", "status", "operation", "payload", "expect"}
MALFORMED_KEYS = {"name", "why", "status", "operation", "payload", "source", "expect_failure"}
ROLLBACK_KEYS = {"name", "why", "calls"}
CALL_KEYS = {"status", "operation", "payload", "source", "expect", "expect_failure"}
MUTATION_ACTIONS = {"set": {"path", "value"}, "del": {"path"}}
# Operation-parse refusals raise from inside the reference's except guard and
# therefore carry the caught exception as __context__; every other refusal
# path raises directly and carries none.
CONTEXT_CARRYING = {
    "operation-three-segments",
    "operation-unknown-operation",
    "operation-unknown-area",
}
# Secret-looking markers carried by corpus rows: typed refusals must not
# echo payload content.
NO_ECHO = ("s3cr3t-fixture", "hunter2-fixture")
# Executed timing bound for the linear FEN-scan probe: the reference
# classifies the 16KiB probe in about 2ms; the quadratic-offset-scan mutant
# needs about 3.3s. 1.0s is ~500x the reference cost.
TIMING_BOUND_S = 1.0
TIMING_PROBE_CHARS = 16384


def _classify(source, status, payload, operation=None):
    """Late-bound access so the mutant battery can rebind the reference."""
    return _REF.classify(source, status, payload, operation)


# -- type-exact snapshots -----------------------------------------------------


def _containers_of(*roots):
    seen, out, stack = set(), [], list(reversed(roots))
    while stack:
        node = stack.pop()
        if isinstance(node, (dict, list)) and id(node) not in seen:
            seen.add(id(node))
            out.append(node)
            stack.extend(dict.values(node) if isinstance(node, dict) else list.__iter__(node))
    return out


def _snap_key(key):
    return str.__str__(key) if isinstance(key, str) else (type(key).__name__, repr(type(key)))


def _snap(obj, _seen=None):
    """Type-exact snapshot; aliases and cycles snapshot as references."""
    seen = {} if _seen is None else _seen
    if isinstance(obj, (dict, list)):
        if id(obj) in seen:
            return ("ref", seen[id(obj)])
        seen[id(obj)] = len(seen)
        if isinstance(obj, dict):
            body = [(type(obj).__name__, _snap_key(k), _snap(v, seen)) for k, v in dict.items(obj)]
        else:
            body = [_snap(v, seen) for v in list.__iter__(obj)]
        return (type(obj).__name__, body)
    if isinstance(obj, str):
        return (type(obj).__name__, str.__str__(obj))
    if isinstance(obj, float) and obj != obj:
        return (type(obj).__name__, "nan")
    return (type(obj).__name__, obj)


# -- source materialization ---------------------------------------------------


class FixtureError(Exception):
    """A corpus mutation list that cannot be materialized or is malformed."""


def _walk(doc, path, where):
    node = doc
    for key in path[:-1]:
        if type(node) is not dict or type(key) is not str or key not in node:
            raise FixtureError(f"{where}: unresolvable path {path}")
        node = node[key]
    if type(node) is not dict or type(path[-1]) is not str:
        raise FixtureError(f"{where}: unresolvable path {path}")
    return node, path[-1]


def _apply_source_mutations(doc, mutations, where):
    for mutation in mutations:
        if type(mutation) is not dict or len(mutation) != 1:
            raise FixtureError(f"{where}: malformed mutation {mutation}")
        (action,) = mutation
        spec = mutation[action]
        if (
            action not in MUTATION_ACTIONS
            or type(spec) is not dict
            or set(spec) != MUTATION_ACTIONS[action]
        ):
            raise FixtureError(f"{where}: malformed mutation {mutation}")
        path = spec["path"]
        if type(path) is not list or not path or not all(type(key) is str for key in path):
            raise FixtureError(f"{where}: malformed path {path}")
        node, last = _walk(doc, path, where)
        if action == "set":
            node[last] = copy.deepcopy(spec["value"])
        else:
            if last not in node:
                raise FixtureError(f"{where}: del of missing key {path}")
            del node[last]


def _materialize_source(mutations, where):
    doc = copy.deepcopy(SOURCE_DOC)
    _apply_source_mutations(doc, mutations, where)
    return doc


# -- executed calls -----------------------------------------------------------


def _check_typed_refusal(error, name, where):
    assert type(error) is _REF.ErrorsError, where
    assert error.failure_class == FAILURE, where
    assert error.code == "malformed_request", where
    assert error.retryable is False, where
    assert error.__cause__ is None, where
    if name in CONTEXT_CARRYING:
        assert error.__context__ is not None, where
    else:
        assert error.__context__ is None, where
    for marker in NO_ECHO:
        assert marker not in str(error), where
        assert marker not in repr(error), where


def _run_verdict_call(status, operation, payload, source_mutations, expect, where):
    source = _materialize_source(source_mutations, where)
    source_snap = _snap(source)
    payload_snap = _snap(payload)
    first = _classify(source, status, payload, operation)
    second = _classify(source, status, payload, operation)
    assert first == expect, where
    assert second == expect, where
    assert first is not second, where  # a fresh dict per classification
    if first["kind"] == "error":
        assert first is not payload["error"], where
        mutated = copy.deepcopy(payload)
        mutated["error"]["message"] = "mutated-after-classification"
        assert first["message"] == expect["message"], where
    assert _snap(payload) == payload_snap, where
    assert _snap(source) == source_snap, where


def _run_refusal_call(status, operation, payload, source_mutations, name, where):
    source = _materialize_source(source_mutations, where)
    source_snap = _snap(source)
    payload_snap = _snap(payload)
    errors = []
    for _ in range(2):
        with pytest.raises(_REF.ErrorsError) as caught:
            _classify(source, status, payload, operation)
        errors.append(caught.value)
    assert errors[0] is not errors[1], where  # a fresh typed error per refusal
    for error in errors:
        _check_typed_refusal(error, name, where)
    assert _snap(payload) == payload_snap, where
    assert _snap(source) == source_snap, where
    return errors


def _run_verdict_row(row, where):
    _run_verdict_call(
        row["status"], row["operation"], row["payload"], row.get("source", []), row["expect"], where
    )


def _run_refusal_row(row, where):
    return _run_refusal_call(
        row["status"], row["operation"], row["payload"], row.get("source", []), row["name"], where
    )


def _run_rollback_row(row):
    where = f"rollback:{row['name']}"
    all_errors = []
    for index, call in enumerate(row["calls"]):
        call_where = f"{where}:call{index}"
        if "expect_failure" in call:
            all_errors += _run_refusal_call(
                call["status"],
                call["operation"],
                call["payload"],
                call["source"],
                row["name"],
                call_where,
            )
        else:
            _run_verdict_call(
                call["status"],
                call["operation"],
                call["payload"],
                call["source"],
                call["expect"],
                call_where,
            )
    ids = {id(error) for error in all_errors}
    assert len(ids) == len(all_errors), where  # no typed error is ever reused


# -- closed-corpus structure ---------------------------------------------------


def _canon(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def _check_mutation_lists(mutations, where):
    assert type(mutations) is list, where
    for mutation in mutations:
        assert type(mutation) is dict and len(mutation) == 1, where
        (action,) = mutation
        assert action in MUTATION_ACTIONS, where
        assert type(mutation[action]) is dict, where
        assert set(mutation[action]) == MUTATION_ACTIONS[action], where
        path = mutation[action]["path"]
        assert type(path) is list and path, where
        assert all(type(key) is str for key in path), where
    _apply_source_mutations(copy.deepcopy(SOURCE_DOC), mutations, where)


def _check_verdict_expect(row, where):
    expect = row["expect"]
    assert type(expect) is dict, where
    if expect["kind"] == "success":
        assert set(expect) == {"kind"}, where
    else:
        assert set(expect) == {"kind", "code", "message", "retryable"}, where
        error = row["payload"]["error"]
        assert expect["code"] == error["code"] and expect["code"] in ENUM, where
        assert expect["message"] == error["message"] and type(expect["message"]) is str, where
        assert expect["retryable"] == error["retryable"] and type(expect["retryable"]) is bool, (
            where
        )


def _check_call(call, where):
    assert type(call) is dict and set(call) <= CALL_KEYS, where
    assert {"status", "operation", "payload", "source"} <= set(call), where
    assert ("expect" in call) != ("expect_failure" in call), where
    if "expect" in call:
        # accepted calls use the real surface: null or a declared operation
        assert type(call["operation"]) is str or call["operation"] is None, where
        if type(call["operation"]) is str:
            assert call["operation"] in OPERATIONS, where
    _check_mutation_lists(call["source"], where)
    if "expect_failure" in call:
        assert call["expect_failure"] in FAILURE_CLASSES, where
    else:
        _check_verdict_expect(call, where)


def _check_row(row, section, where):
    assert type(row) is dict, where
    assert type(row["name"]) is str and row["name"], where
    assert type(row["why"]) is str and row["why"], where
    if section in VERDICT_SECTIONS:
        assert set(row) == VERDICT_KEYS, where
        assert type(row["status"]) is int and (
            200 <= row["status"] <= 299 or 400 <= row["status"] <= 599
        ), where
        assert type(row["payload"]) is dict, where
        _check_call(
            {key: row[key] for key in VERDICT_KEYS - {"name", "why"}} | {"source": []}, where
        )
    elif section == "malformed":
        assert set(row) == MALFORMED_KEYS, where
        assert row["expect_failure"] in FAILURE_CLASSES, where
        _check_call({key: row[key] for key in MALFORMED_KEYS - {"name", "why"}}, where)
    else:
        assert set(row) == ROLLBACK_KEYS, where
        calls = row["calls"]
        assert type(calls) is list and calls, where
        for index, call in enumerate(calls):
            _check_call(call, f"{where}:call{index}")


def _check_section(cases, section):
    """The manifest closure for one section: digests, order, key shapes."""
    rows = cases[section]
    assert type(rows) is list and rows, section
    manifest = cases["section_manifests"][section]
    assert list(manifest) == [row["name"] for row in rows], section
    computed = {row["name"]: hashlib.sha256(_canon(row)).hexdigest() for row in rows}
    assert manifest == computed, section
    for row in rows:
        _check_row(row, section, f"{section}:{row.get('name')}")


def _check(cases):
    assert type(cases) is dict
    assert set(cases) == TOP_KEYS, f"top keys {sorted(cases)}"
    assert type(cases["schema_version"]) is int and cases["schema_version"] == 1
    assert cases["contract"] == "data/contracts/control_plane_errors.yaml"
    assert cases["contract_schema_version"] == CONTRACT_DOC["schema_version"]
    assert cases["source"] == "data/contracts/control-plane.yaml"
    assert cases["source_manifest"] == hashlib.sha256(_canon(SOURCE_DOC)).hexdigest()
    assert type(cases["notes"]) is str and "separate binding" in cases["notes"]
    assert "no production semantics" in cases["notes"].lower()
    assert set(cases["section_manifests"]) == set(SECTIONS)
    names = []
    for section in SECTIONS:
        _check_section(cases, section)
        names.extend(row["name"] for row in cases[section])
    assert len(names) == len(set(names))


def test_fixture_structure():
    _check(CASES)


def test_fixture_matches_generator():
    assert _GEN.dump(_GEN.build()) == FIXTURE.read_text()


@pytest.mark.parametrize("section", SECTIONS)
def test_closed_manifest_detects_reorder_drop_and_extra(section):
    manifest = CASES["section_manifests"][section]
    names = [row["name"] for row in CASES[section]]
    assert list(manifest) == names
    assert len(names) == len(set(names))
    for mutant_rows in (
        list(reversed(CASES[section])),
        CASES[section][1:],
        [*CASES[section], copy.deepcopy(CASES[section][0])],
    ):
        mutant = copy.deepcopy(CASES)
        mutant[section] = mutant_rows
        with pytest.raises(AssertionError):
            _check_section(mutant, section)


def test_row_substitution_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                mutant_rows = copy.deepcopy(rows)
                replacement = copy.deepcopy(mutant_rows[donor])
                replacement["name"] = mutant_rows[target]["name"]
                mutant_rows[target] = replacement
                mutant = {**CASES, section: mutant_rows}
                with pytest.raises(AssertionError):
                    _check_section(mutant, section)


def test_each_row_field_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                shared = (set(rows[target]) & set(rows[donor])) - {"name"}
                for field in shared:
                    if rows[target][field] == rows[donor][field]:
                        continue
                    mutant_rows = copy.deepcopy(rows)
                    mutant_rows[target][field] = copy.deepcopy(rows[donor][field])
                    mutant = {**CASES, section: mutant_rows}
                    with pytest.raises(AssertionError):
                        _check_section(mutant, section)


def test_structure_mutations_fail():
    for bad in (True, 1.0, "1", 0, 2):
        mutant = copy.deepcopy(CASES)
        mutant["schema_version"] = bad
        with pytest.raises(AssertionError):
            _check(mutant)
    for section in SECTIONS:
        mutant = copy.deepcopy(CASES)
        mutant[section][0]["rogue"] = None
        with pytest.raises(AssertionError):
            _check(mutant)
    mutant = copy.deepcopy(CASES)
    mutant["rogue_section"] = []
    with pytest.raises(AssertionError):
        _check(mutant)
    mutant = copy.deepcopy(CASES)
    mutant["source_manifest"] = "0" * 64
    with pytest.raises(AssertionError):
        _check(mutant)


def test_malformed_source_mutations_refuse():
    for mutations in (
        [{"set": None}],
        [{"del": None}],
        [{"set": []}],
        [{"append": {"path": ["areas"], "value": 1}}],
        [{"set": {"path": [], "value": 1}}],
    ):
        with pytest.raises(FixtureError):
            _materialize_source(mutations, "probe")


def test_unresolvable_source_mutation_paths_refuse():
    for mutations in (
        [{"set": {"path": ["areas", "no_such_area", "ops"], "value": {}}}],
        [{"del": {"path": ["areas", "identity", "ops", "no_such_op"]}}],
    ):
        with pytest.raises(FixtureError):
            _materialize_source(mutations, "probe")


# -- executed rows --------------------------------------------------------------


def _section_names(section):
    return [row["name"] for row in CASES[section]]


def _row_by_name(section, name):
    return next(row for row in CASES[section] if row["name"] == name)


@pytest.mark.parametrize(
    "section,name",
    [(section, name) for section in VERDICT_SECTIONS for name in _section_names(section)],
    ids=lambda value: value if value in SECTIONS else None,
)
def test_verdict_rows_execute_with_purity_and_determinism(section, name):
    _run_verdict_row(_row_by_name(section, name), f"{section}:{name}")


@pytest.mark.parametrize("name", _section_names("malformed"))
def test_malformed_rows_refuse_typed_with_purity(name):
    _run_refusal_row(_row_by_name("malformed", name), f"malformed:{name}")


@pytest.mark.parametrize("name", _section_names("rollback"))
def test_rollback_rows_execute_atomic_sequences(name):
    _run_rollback_row(_row_by_name("rollback", name))


# -- coverage pins ----------------------------------------------------------------


def test_happy_section_covers_every_closed_enum_member():
    names = set(_section_names("happy"))
    assert {f"enum-{code.replace('_', '-')}" for code in ENUM} <= names
    assert len(ENUM) == 14


def test_happy_section_covers_every_declared_operation():
    names = set(_section_names("happy"))
    assert {f"operation-{op.replace('.', '-')}-example" for op in OPERATIONS} <= names
    assert len(OPERATIONS) == 14


def test_boundary_section_pins_bounds_and_near_misses():
    names = set(_section_names("boundary"))
    assert {
        "status-200-edge",
        "status-299-edge",
        "status-400-edge",
        "status-599-edge",
        "depth-eight-nesting-accepted",
        "dict-256-extras-accepted",
        "list-256-extras-accepted",
        "error-message-token-run-31-allowed",
        "error-key-token-run-31-allowed",
        "fen-seven-ranks-allowed",
        "fen-rank-sum-seven-allowed",
        "fen-rank-sum-nine-allowed",
        "fen-44-near-miss-allowed",
        "fen-middle-rank-bad-allowed",
        "short-san-text-gap-allowed-2xx",
        "short-san-text-gap-allowed-error",
    } <= names


def test_malformed_section_pins_status_classes_and_envelope_shape():
    names = set(_section_names("malformed"))
    assert {
        "status-zero",
        "status-100",
        "status-199",
        "status-300",
        "status-399",
        "status-600",
        "status-bool-true",
        "status-float",
        "status-string",
        "status-null",
        "error-missing",
        "error-missing-code",
        "error-missing-message",
        "error-missing-retryable",
        "error-code-outside-enum",
        "hostile-source-schema-version-bool",
        "hostile-source-enum-nonstring-member",
        "hostile-source-shape-required-flipped",
    } <= names


def test_malformed_section_pins_fen_and_token_run_rules():
    names = set(_section_names("malformed"))
    assert {
        "fen-plain-2xx",
        "fen-glued-suffix-letter",
        "fen-glued-colon-prefix",
        "fen-slash-prefix",
        "fen-left-edge-digit",
        "fen-right-edge-digit",
        "fen-trailing-piece",
        "fen-nine-ranks",
        "fen-zero-digit-08",
        "fen-zero-digit-0p7",
        "fen-in-list-2xx",
        "fen-in-declared-token-2xx",
        "fen-in-error-message-4xx",
        "fen-nested-extra-4xx",
        "error-message-token-run-32",
        "error-key-token-run-32",
        "error-key-token-run-32-nested",
    } <= names


def test_rollback_section_pins_atomic_classifier_semantics():
    names = set(_section_names("rollback"))
    assert {
        "refuse-then-classify-unchanged",
        "classify-refuse-classify",
        "repeated-refusals-fresh-errors",
        "refusal-leaves-nested-inputs-bit-identical",
        "accepted-result-detached-from-payload",
        "refuse-with-hostile-source-then-clean-source",
    } <= names


# -- derived hostile probes (values JSON cannot represent) ---------------------


class _StrSub(str):
    pass


class _IntSub(int):
    pass


class _DictSub(dict):
    pass


class _ListSub(list):
    pass


def _base_envelope():
    return copy.deepcopy(_row_by_name("happy", "enum-not-found")["payload"])


def _derived_probes():
    """(label, status, operation, payload) refusal probes derived from pinned
    rows; every value here is outside JSON's representational scope."""
    probes = []

    def add(label, payload, status=400, operation=None):
        probes.append((label, status, operation, payload))

    payload = _base_envelope()
    payload["error"]["message"] = "\ud800"
    add("message-high-surrogate", payload)
    payload = _base_envelope()
    payload["error"]["message"] = "\udc00"
    add("message-low-surrogate", payload)
    payload = _base_envelope()
    payload["extra"] = "\udc00"
    add("extra-low-surrogate", payload)
    payload = _base_envelope()
    payload["x\udc00"] = "bad"
    add("key-low-surrogate", payload)
    payload = _base_envelope()
    payload["extra"] = float("inf")
    add("extra-positive-infinity", payload)
    payload = _base_envelope()
    payload["extra"] = float("-inf")
    add("extra-negative-infinity", payload)
    add("success-nan-extra", {"extra": float("nan")}, status=200)
    add("success-positive-infinity-extra", {"extra": float("inf")}, status=200)
    payload = _base_envelope()
    payload["extra"] = _IntSub(1)
    add("extra-int-subclass", payload)
    payload = _base_envelope()
    payload["extra"] = object()
    add("extra-plain-object", payload)
    payload = _base_envelope()
    payload[1] = "bad"
    add("non-string-key", payload)
    add("payload-dict-subclass", _DictSub(_base_envelope()))
    payload = _base_envelope()
    payload["error"] = _DictSub(payload["error"])
    add("error-dict-subclass", payload)
    payload = _base_envelope()
    payload["error"]["message"] = _StrSub("fixture detail")
    add("message-str-subclass", payload)
    payload = {_StrSub("extra"): "v", **_base_envelope()}
    add("key-str-subclass", payload)
    add("status-int-subclass", _base_envelope(), status=_IntSub(400))
    payload = _base_envelope()
    payload["extra"] = _ListSub([1, 2])
    add("extra-list-subclass", payload)
    return probes


_DERIVED_PROBES = _derived_probes()


def _run_derived_probe(probe):
    label, status, operation, payload = probe
    payload_snap = _snap(payload)
    errors = []
    for _ in range(2):
        with pytest.raises(_REF.ErrorsError) as caught:
            _classify(copy.deepcopy(SOURCE_DOC), status, payload, operation)
        errors.append(caught.value)
    assert errors[0] is not errors[1], label
    for error in errors:
        assert error.failure_class == FAILURE, label
        assert error.code == "malformed_request", label
        assert error.retryable is False, label
        assert error.__cause__ is None, label
    assert _snap(payload) == payload_snap, label


@pytest.mark.parametrize("label", [label for label, _, _, _ in _DERIVED_PROBES])
def test_derived_hostile_probes_refuse_typed(label):
    (probe,) = [probe for probe in _DERIVED_PROBES if probe[0] == label]
    _run_derived_probe(probe)


def _timing_probe():
    """Executed bound: the linear FEN scan classifies a 16KiB clean string in
    milliseconds; the quadratic-offset-scan mutant needs seconds."""
    payload = {"extra": "p" * TIMING_PROBE_CHARS}
    started = time.perf_counter()
    assert _classify(copy.deepcopy(SOURCE_DOC), 200, payload) == {"kind": "success"}
    assert time.perf_counter() - started < TIMING_BOUND_S


def test_linear_scan_timing_probe():
    _timing_probe()


# -- mutant battery ---------------------------------------------------------------


def _fixture_red():
    """Labels of executed fixture checks that disagree with the reference
    currently bound; empty when green. Every label comes from a row or probe
    executed through classify(): no source-text or table-shape check counts."""
    red = []
    for section in VERDICT_SECTIONS:
        for row in CASES[section]:
            try:
                _run_verdict_row(row, f"{section}:{row['name']}")
            except BaseException:  # noqa: BLE001
                red.append(f"{section}:{row['name']}")
    for row in CASES["malformed"]:
        try:
            _run_refusal_row(row, f"malformed:{row['name']}")
        except BaseException:  # noqa: BLE001
            red.append(f"malformed:{row['name']}")
    for row in CASES["rollback"]:
        try:
            _run_rollback_row(row)
        except BaseException:  # noqa: BLE001
            red.append(f"rollback:{row['name']}")
    for probe in _DERIVED_PROBES:
        try:
            _run_derived_probe(probe)
        except BaseException:  # noqa: BLE001
            red.append(f"probe:{probe[0]}")
    try:
        _timing_probe()
    except BaseException:  # noqa: BLE001
        red.append("probe:linear-scan-timing")
    return red


# Edits that must NOT change behavior: pure reorders of equivalent checks.
EQUIVALENT_EDITS = {
    "field-loop-order": (
        'for field in ("code", "message", "retryable"):',
        'for field in ("message", "code", "retryable"):',
    ),
    "status-range-order": (
        "200 <= status <= 299 or 400 <= status <= 599",
        "400 <= status <= 599 or 200 <= status <= 299",
    ),
    "secret-set-order": (
        '{"key_material", "password_hash_client", "token", "secret"}',
        '{"secret", "token", "password_hash_client", "key_material"}',
    ),
}


def _reference_source():
    return "\n".join(
        inspect.getsource(f)
        for f in (
            _REF._text,
            _REF._tokens,
            _REF._fen_placement_in,
            _REF._safe_key,
            _REF._json_safe,
            _REF._source,
            _REF.classify,
        )
    )


def _equivalent_classify(name):
    before, replacement = EQUIVALENT_EDITS[name]
    source = _reference_source()
    assert source.count(before) == 1, name
    scope = dict(vars(_REF))
    exec(  # noqa: S102
        compile(ast.parse(source.replace(before, replacement, 1)), f"<equivalent:{name}>", "exec"),
        scope,
    )
    return scope["classify"]


def test_reference_edits_apply():
    for name in _REF.REFERENCE_MUTANTS:
        _REF._mutant(name)
    for name in EQUIVALENT_EDITS:
        _equivalent_classify(name)


def test_reference_is_green():
    assert _fixture_red() == []


@pytest.mark.parametrize("name", sorted(_REF.REFERENCE_MUTANTS))
def test_reference_mutants_turn_the_fixture_red(name, monkeypatch):
    monkeypatch.setattr(_REF, "classify", _REF._mutant(name))
    assert _fixture_red() != [], name


@pytest.mark.parametrize("name", sorted(EQUIVALENT_EDITS))
def test_equivalent_edits_keep_the_fixture_green(name, monkeypatch):
    monkeypatch.setattr(_REF, "classify", _equivalent_classify(name))
    assert _fixture_red() == [], name
