# ruff: noqa: E501  (exact contract literals)
"""T0456: closed, executable fixture for the public identity rate-limit contract.

The corpus (tests/fixtures/rate-limit/cases.json, generated by
tools/rate_limit_fixture_generate.py) pins happy, boundary, malformed and
rollback rows for the fail-closed admission decision declared in
data/contracts/rate_limit.yaml and executes every row against the T0455
test-only synthetic reference decision() as a separate binding; a later
implement task (T0458) must independently implement the admission decision
and rebind these rows. Expectations are authored from the structured
contract, never computed by the reference. Python-level hostiles that JSON
cannot represent (built-in subclasses, NaN/infinity, lone surrogates, plain
objects) are derived in code from pinned rows; the mutant battery's kills
all come from executed fixture checks, never source-text checks.
"""

from __future__ import annotations

import ast
import copy
import hashlib
import inspect
import json
from pathlib import Path

import pytest
import yaml

import tests.test_t0455_rate_limit_contract as _REF
import tools.rate_limit_fixture_generate as _GEN

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "rate-limit" / "cases.json"
CASES = json.loads(FIXTURE.read_text())
SOURCE_DOC = yaml.safe_load((ROOT / CASES["source"]).read_text())
CONTRACT_DOC = yaml.safe_load((ROOT / CASES["contract"]).read_text())
OPS = tuple(_REF.OPS)
MAX_CLOCK = _REF.MAX_CLOCK
FAILURE_CODES = ("malformed_request", "idempotency_conflict", "internal")
OUTCOMES = ("admit", "replay", "deny")
SECTIONS = ("happy", "boundary", "malformed", "rollback")
VERDICT_SECTIONS = ("happy", "boundary")
TOP_KEYS = {
    "schema_version",
    "contract",
    "contract_schema_version",
    "source",
    "source_manifest",
    "notes",
    "section_manifests",
    *SECTIONS,
}
CALL_KEYS = {
    "operation",
    "account",
    "source",
    "now",
    "policy",
    "state",
    "replay",
    "body_same",
    "store_available",
    "effect_ok",
}
RECORD_KEYS = {"operation", "scope", "opaque", "window", "count"}
VERDICT_ROW_KEYS = {"name", "why", "call", "expect"}
MALFORMED_ROW_KEYS = {"name", "why", "call", "expect_failure"}
ROLLBACK_ROW_KEYS = {"name", "why", "calls"}
STEP_KEYS = {"call", "expect", "expect_failure"}
_UNSET = object()


def _decide(**kwargs):
    """Late-bound access so the mutant battery can rebind the reference."""
    return _REF.decision(**kwargs)


# -- type-exact snapshots -----------------------------------------------------


def _snap(obj, _seen=None):
    """Type-exact snapshot; aliases and cycles snapshot as references."""
    seen = {} if _seen is None else _seen
    if isinstance(obj, (dict, list)):
        if id(obj) in seen:
            return ("ref", seen[id(obj)])
        seen[id(obj)] = len(seen)
        if isinstance(obj, dict):
            body = [
                (
                    type(obj).__name__,
                    str.__str__(k) if isinstance(k, str) else (type(k).__name__, repr(type(k))),
                    _snap(v, seen),
                )
                for k, v in dict.items(obj)
            ]
        else:
            body = [_snap(v, seen) for v in list.__iter__(obj)]
        return (type(obj).__name__, body)
    if isinstance(obj, str):
        return (type(obj).__name__, str.__str__(obj))
    if isinstance(obj, float) and obj != obj:
        return (type(obj).__name__, "nan")
    if obj is None or type(obj) in (bool, int, float):
        return (type(obj).__name__, obj)
    return (type(obj).__name__, repr(type(obj)))


# -- state adapter --------------------------------------------------------------


def _to_ref_state(records):
    """Fixture records to the reference's tuple-keyed snapshot."""
    return {
        (rec["operation"], rec["scope"], rec["opaque"]): (rec["window"], rec["count"])
        for rec in records
    }


def _canon_records(records):
    return sorted(
        (json.dumps(rec, sort_keys=True, separators=(",", ":")) for rec in records),
    )


def _canon_ref_state(state):
    return _canon_records(
        {
            "operation": key[0],
            "scope": key[1],
            "opaque": key[2],
            "window": value[0],
            "count": value[1],
        }
        for key, value in state.items()
    )


def _args(call, ref_state=_UNSET):
    args = dict(call)
    args["state"] = _to_ref_state(call["state"]) if ref_state is _UNSET else ref_state
    return args


# -- executed calls ---------------------------------------------------------------


def _run_verdict_call(call, expect, where, ref_state=_UNSET):
    outcome = expect["outcome"]
    assert outcome in OUTCOMES, where
    args = _args(call, ref_state)
    snap = _snap(args)
    if outcome == "deny":
        errors = []
        for run_args in (copy.deepcopy(args), args):  # second run borrows the caller's objects
            with pytest.raises(_REF.Refusal) as caught:
                _decide(**run_args)
            assert type(caught.value) is _REF.Refusal, where
            assert caught.value.code == "rate_limited", where
            errors.append(caught.value)
        assert errors[0] is not errors[1], where
        assert _snap(args) == snap, where  # a denial commits neither counter
        return
    results = []
    for run_args in (copy.deepcopy(args), args):  # second run borrows the caller's objects
        kind, new_state = _decide(**run_args)
        assert kind == outcome, where
        assert new_state is not run_args["state"], where  # detached result state
        assert _canon_ref_state(new_state) == _canon_records(expect["state"]), where
        results.append(new_state)
    assert results[0] is not results[1], where
    assert _snap(args) == snap, where  # the decision never mutates its inputs


def _run_refusal_call(call, code, where, ref_state=_UNSET):
    assert code in FAILURE_CODES, where
    args = _args(call, ref_state)
    snap = _snap(args)
    errors = []
    for run_args in (copy.deepcopy(args), args):  # second run borrows the caller's objects
        with pytest.raises(_REF.Refusal) as caught:
            _decide(**run_args)
        errors.append(caught.value)
    assert errors[0] is not errors[1], where  # a fresh typed error per refusal
    for error in errors:
        assert type(error) is _REF.Refusal, where
        assert error.code == code, where
    assert _snap(args) == snap, where  # a refusal commits nothing
    return errors


def _run_verdict_row(row, where):
    _run_verdict_call(row["call"], row["expect"], where)


def _run_refusal_row(row, where):
    return _run_refusal_call(row["call"], row["expect_failure"], where)


def _run_rollback_row(row):
    where = f"rollback:{row['name']}"
    threaded = None
    all_errors = []
    for index, entry in enumerate(row["calls"]):
        step_where = f"{where}:call{index}"
        call = entry["call"]
        if threaded is not None:
            # The pinned chain: each step starts from exactly the state the
            # previous step pinned as its outcome.
            assert _canon_records(call["state"]) == threaded, step_where
        if "expect_failure" in entry:
            all_errors += _run_refusal_call(call, entry["expect_failure"], step_where)
            threaded = _canon_records(call["state"])
        else:
            _run_verdict_call(call, entry["expect"], step_where)
            threaded = _canon_records(entry["expect"]["state"])
    ids = {id(error) for error in all_errors}
    assert len(ids) == len(all_errors), where  # no typed error is ever reused


# -- closed-corpus structure ---------------------------------------------------


def _canon(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def _check_record(rec, where):
    assert type(rec) is dict and set(rec) == RECORD_KEYS, where
    assert type(rec["operation"]) is str, where
    assert type(rec["scope"]) is str and rec["scope"], where
    assert type(rec["opaque"]) is str and rec["opaque"], where
    assert type(rec["window"]) is int and rec["window"] >= 0, where
    assert type(rec["count"]) is int and rec["count"] >= 0, where


def _check_strict_call(call, where):
    assert type(call) is dict and set(call) == CALL_KEYS, where
    assert call["operation"] in OPS, where
    for label in ("account", "source"):
        value = call[label]
        assert type(value) is str and value.startswith("opaque:"), where
    assert type(call["now"]) is int and 0 <= call["now"] <= MAX_CLOCK, where
    policy = call["policy"]
    assert type(policy) is dict and set(policy) == {"version", "account", "source"}, where
    assert type(policy["version"]) is int and policy["version"] >= 1, where
    for label in ("account", "source"):
        cfg = policy[label]
        assert type(cfg) is dict and set(cfg) == {"capacity", "window_ms"}, where
        for key in ("capacity", "window_ms"):
            assert type(cfg[key]) is int and 1 <= cfg[key] <= MAX_CLOCK, where
    assert type(call["state"]) is list, where
    for index, rec in enumerate(call["state"]):
        _check_record(rec, f"{where}:state{index}")
    keys = [(rec["operation"], rec["scope"], rec["opaque"]) for rec in call["state"]]
    assert len(keys) == len(set(keys)), where
    assert call["replay"] in ("new", "cached"), where
    for flag in ("body_same", "store_available", "effect_ok"):
        assert type(call[flag]) is bool, where


def _check_verdict_expect(row, where):
    expect = row["expect"]
    assert type(expect) is dict and set(expect) == {"outcome", "state"}, where
    outcome = expect["outcome"]
    assert outcome in OUTCOMES, where
    assert type(expect["state"]) is list, where
    for index, rec in enumerate(expect["state"]):
        _check_record(rec, f"{where}:expect{index}")
    call = row["call"]
    if outcome == "replay":
        assert call["replay"] == "cached" and call["body_same"] is True, where
        assert _canon_records(expect["state"]) == _canon_records(call["state"]), where
    elif outcome == "deny":
        assert call["replay"] == "new", where
        assert _canon_records(expect["state"]) == _canon_records(call["state"]), where
    else:
        assert call["replay"] == "new", where


def _check_lenient_call(call, where):
    """Malformed rows carry hostile values; only the envelope is closed."""
    assert type(call) is dict and set(call) == CALL_KEYS, where
    assert type(call["state"]) is list, where
    for index, rec in enumerate(call["state"]):
        assert type(rec) is dict and set(rec) == RECORD_KEYS, f"{where}:state{index}"


def _check_row(row, section, where):
    assert type(row) is dict, where
    assert type(row["name"]) is str and row["name"], where
    assert type(row["why"]) is str and row["why"], where
    if section in VERDICT_SECTIONS:
        assert set(row) == VERDICT_ROW_KEYS, where
        _check_strict_call(row["call"], where)
        _check_verdict_expect(row, where)
    elif section == "malformed":
        assert set(row) == MALFORMED_ROW_KEYS, where
        assert row["expect_failure"] in FAILURE_CODES, where
        _check_lenient_call(row["call"], where)
    else:
        assert set(row) == ROLLBACK_ROW_KEYS, where
        calls = row["calls"]
        assert type(calls) is list and calls, where
        for index, entry in enumerate(calls):
            step_where = f"{where}:call{index}"
            assert type(entry) is dict and set(entry) <= STEP_KEYS, step_where
            assert "call" in entry, step_where
            assert ("expect" in entry) != ("expect_failure" in entry), step_where
            if "expect_failure" in entry:
                assert entry["expect_failure"] in FAILURE_CODES, step_where
                _check_lenient_call(entry["call"], step_where)
            else:
                _check_strict_call(entry["call"], step_where)
                _check_verdict_expect(
                    {"call": entry["call"], "expect": entry["expect"]}, step_where
                )


def _check_section(cases, section):
    """The manifest closure for one section: digests, order, key shapes."""
    rows = cases[section]
    assert type(rows) is list and rows, section
    manifest = cases["section_manifests"][section]
    assert list(manifest) == [row["name"] for row in rows], section
    computed = {row["name"]: hashlib.sha256(_canon(row)).hexdigest() for row in rows}
    assert manifest == computed, section
    for row in rows:
        _check_row(row, section, f"{section}:{row.get('name')}")


def _check(cases):
    assert type(cases) is dict
    assert set(cases) == TOP_KEYS, f"top keys {sorted(cases)}"
    assert type(cases["schema_version"]) is int and cases["schema_version"] == 1
    assert cases["contract"] == "data/contracts/rate_limit.yaml"
    assert cases["contract_schema_version"] == CONTRACT_DOC["schema_version"]
    assert cases["source"] == "data/contracts/control-plane.yaml"
    assert cases["source_manifest"] == hashlib.sha256(_canon(SOURCE_DOC)).hexdigest()
    assert type(cases["notes"]) is str and "separate binding" in cases["notes"]
    assert "no production semantics" in cases["notes"].lower()
    assert "skips all request, policy, state and store validation" in cases["notes"]
    assert set(cases["section_manifests"]) == set(SECTIONS)
    names = []
    for section in SECTIONS:
        _check_section(cases, section)
        names.extend(row["name"] for row in cases[section])
    assert len(names) == len(set(names))


def test_fixture_structure():
    _check(CASES)


def test_fixture_matches_generator():
    assert _GEN.dump(_GEN.build()) == FIXTURE.read_text()


@pytest.mark.parametrize("section", SECTIONS)
def test_closed_manifest_detects_reorder_drop_and_extra(section):
    manifest = CASES["section_manifests"][section]
    names = [row["name"] for row in CASES[section]]
    assert list(manifest) == names
    assert len(names) == len(set(names))
    for mutant_rows in (
        list(reversed(CASES[section])),
        CASES[section][1:],
        [*CASES[section], copy.deepcopy(CASES[section][0])],
    ):
        mutant = copy.deepcopy(CASES)
        mutant[section] = mutant_rows
        with pytest.raises(AssertionError):
            _check_section(mutant, section)


def test_row_substitution_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                mutant_rows = copy.deepcopy(rows)
                replacement = copy.deepcopy(mutant_rows[donor])
                replacement["name"] = mutant_rows[target]["name"]
                mutant_rows[target] = replacement
                mutant = {**CASES, section: mutant_rows}
                with pytest.raises(AssertionError):
                    _check_section(mutant, section)


def test_each_row_field_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                shared = (set(rows[target]) & set(rows[donor])) - {"name"}
                for field in shared:
                    if rows[target][field] == rows[donor][field]:
                        continue
                    mutant_rows = copy.deepcopy(rows)
                    mutant_rows[target][field] = copy.deepcopy(rows[donor][field])
                    mutant = {**CASES, section: mutant_rows}
                    with pytest.raises(AssertionError):
                        _check_section(mutant, section)


def test_structure_mutations_fail():
    for bad in (True, 1.0, "1", 0, 2):
        mutant = copy.deepcopy(CASES)
        mutant["schema_version"] = bad
        with pytest.raises(AssertionError):
            _check(mutant)
    for section in SECTIONS:
        mutant = copy.deepcopy(CASES)
        mutant[section][0]["rogue"] = None
        with pytest.raises(AssertionError):
            _check(mutant)
    mutant = copy.deepcopy(CASES)
    mutant["rogue_section"] = []
    with pytest.raises(AssertionError):
        _check(mutant)
    mutant = copy.deepcopy(CASES)
    mutant["source_manifest"] = "0" * 64
    with pytest.raises(AssertionError):
        _check(mutant)


# -- executed rows --------------------------------------------------------------


def _section_names(section):
    return [row["name"] for row in CASES[section]]


def _row_by_name(section, name):
    return next(row for row in CASES[section] if row["name"] == name)


@pytest.mark.parametrize(
    "section,name",
    [(section, name) for section in VERDICT_SECTIONS for name in _section_names(section)],
    ids=lambda value: value if value in SECTIONS else None,
)
def test_verdict_rows_execute_with_purity_and_determinism(section, name):
    _run_verdict_row(_row_by_name(section, name), f"{section}:{name}")


@pytest.mark.parametrize("name", _section_names("malformed"))
def test_malformed_rows_refuse_typed_with_purity(name):
    _run_refusal_row(_row_by_name("malformed", name), f"malformed:{name}")


@pytest.mark.parametrize("name", _section_names("rollback"))
def test_rollback_rows_execute_atomic_chains(name):
    _run_rollback_row(_row_by_name("rollback", name))


# -- coverage pins ----------------------------------------------------------------


def test_happy_section_pins():
    assert {
        "admit-first-empty-login",
        "admit-first-empty-register",
        "admit-second-slot-both-buckets",
        "admit-other-operation-own-buckets",
        "admit-other-account-own-bucket",
        "admit-other-source-own-bucket",
        "admit-policy-version-high",
        "admit-capacity-and-clock-max",
        "admit-window-one-ms",
        "replay-cached-identical",
        "replay-cached-empty-state",
        "admit-preserves-unrelated-records",
    } <= set(_section_names("happy"))


def test_boundary_section_pins():
    assert {
        "admit-last-account-slot",
        "deny-account-at-capacity",
        "deny-source-at-capacity",
        "deny-account-not-evaded-by-source-rotation",
        "deny-source-not-evaded-by-account-rotation",
        "admit-at-exact-window-start",
        "deny-one-tick-before-window-start",
        "admit-same-clock-mid-window",
        "admit-now-max-clock",
        "admit-capacity-one-first-attempt",
        "deny-capacity-one-second-attempt",
        "replay-at-full-bucket",
        "deny-second-bucket-leaves-first-uncharged",
        "admit-old-window-full-count-dropped",
        "admit-charges-exactly-the-two-scope-buckets",
        "state-unknown-scope-record-preserved",
    } <= set(_section_names("boundary"))


def test_malformed_section_pins():
    names = set(_section_names("malformed"))
    assert {
        "operation-undeclared",
        "operation-nonstring",
        "operation-null",
        "account-raw-email",
        "account-missing-opaque-prefix",
        "account-nonstring",
        "source-raw-ip",
        "source-nonstring",
        "now-bool",
        "now-negative",
        "now-float",
        "now-string",
        "now-past-max-clock",
        "policy-null",
        "policy-missing-account",
        "policy-extra-key",
        "policy-version-zero",
        "policy-version-negative",
        "policy-version-bool",
        "policy-capacity-zero",
        "policy-capacity-negative",
        "policy-capacity-bool",
        "policy-capacity-float",
        "policy-capacity-past-max-clock",
        "policy-window-zero",
        "policy-window-past-max-clock",
        "policy-config-missing-window",
        "policy-config-extra-key",
        "replay-token-undeclared",
        "replay-token-nonstring",
        "body-same-nonbool-int",
        "body-same-nonbool-null",
        "body-same-nonbool-int-cached",
        "body-same-nonbool-zero-cached",
        "body-same-nonbool-string-cached",
        "body-same-nonbool-list-cached",
        "body-same-nonbool-null-cached",
        "malformed-operation-with-corrupt-state",
        "malformed-policy-with-corrupt-state",
        "conflict-cached-different-body",
        "conflict-at-full-bucket",
        "conflict-with-malformed-operation",
        "store-unavailable",
        "store-unavailable-at-full-bucket",
        "effect-failure",
        "state-record-count-bool",
        "state-record-count-negative",
        "state-record-window-negative",
        "state-record-future-window",
        "state-record-count-over-capacity",
    } <= names


def test_malformed_section_covers_every_failure_code():
    codes = {row["expect_failure"] for row in CASES["malformed"]}
    assert codes == set(FAILURE_CODES)


def test_outcomes_cover_admit_replay_and_deny():
    outcomes = {row["expect"]["outcome"] for section in VERDICT_SECTIONS for row in CASES[section]}
    assert outcomes == set(OUTCOMES)
    assert all(
        row["expect"]["outcome"] != "deny" for row in CASES["happy"]
    )  # denials are boundary behavior


def test_rollback_section_pins():
    assert {
        "admit-deny-replay-readmit-chain",
        "conflict-then-replay-then-admit-chain",
        "store-down-then-recovered-chain",
        "effect-failure-then-success-chain",
        "malformed-then-valid-unchanged-chain",
        "replay-never-double-charges-chain",
        "window-rollover-chain",
        "operation-scope-interleave-chain",
        "rotation-after-deny-chain",
        "failure-mid-chain-poisons-nothing",
    } <= set(_section_names("rollback"))


def test_source_declares_fixture_codes_for_both_operations():
    for op in OPS:
        area, name = op.split(".")
        errors = set(SOURCE_DOC["areas"][area]["ops"][name]["errors"])
        assert {"rate_limited", "malformed_request", "idempotency_conflict", "internal"} <= errors


def test_contract_scope_and_reference_status():
    role = CONTRACT_DOC["contract"]["role"]
    assert sorted(role["scope"]) == sorted(OPS)
    assert role["status"] == "reference-only-no-live-enforcement-claimed"
    results = CONTRACT_DOC["contract"]["results"]
    assert "rate_limited" in results["deny"]
    assert "no-counter-change" in results["replay"]
    assert "no-counter-change" in results["conflict"]


def test_state_adapter_roundtrip():
    for section in SECTIONS:
        rows = CASES[section]
        calls = (
            [row["call"] for row in rows]
            if section != "rollback"
            else [entry["call"] for row in rows for entry in row["calls"]]
        )
        for call in calls:
            if any(
                type(rec["window"]) is not int or type(rec["count"]) is not int
                for rec in call["state"]
            ):
                continue  # hostile records are the point of those rows
            assert _canon_ref_state(_to_ref_state(call["state"])) == _canon_records(call["state"])


# -- derived hostile probes (values JSON cannot represent) ---------------------


class _StrSub(str):
    pass


class _IntSub(int):
    pass


class _DictSub(dict):
    pass


def _probe_base():
    return copy.deepcopy(_row_by_name("happy", "admit-first-empty-login")["call"])


def _field_probes():
    """(label, edited call, refusal code) probes: every value here is outside
    JSON's representational scope."""
    probes = []

    def add(label, edit, code="malformed_request"):
        call = _probe_base()
        edit(call)
        probes.append((label, call, code))

    add("operation-str-subclass", lambda c: c.update(operation=_StrSub("identity.login")))
    add("operation-plain-object", lambda c: c.update(operation=object()))
    add("account-str-subclass", lambda c: c.update(account=_StrSub("opaque:account")))
    add("account-plain-object", lambda c: c.update(account=object()))
    add("source-str-subclass", lambda c: c.update(source=_StrSub("opaque:source")))
    add("now-int-subclass", lambda c: c.update(now=_IntSub(0)))
    add("now-nan", lambda c: c.update(now=float("nan")))
    add("now-infinity", lambda c: c.update(now=float("inf")))
    add("policy-dict-subclass", lambda c: c.update(policy=_DictSub(c["policy"])))
    add("policy-version-int-subclass", lambda c: c["policy"].update(version=_IntSub(1)))
    add("policy-capacity-nan", lambda c: c["policy"]["account"].update(capacity=float("nan")))
    return probes


def _state_probes():
    """(label, hostile reference state) probes refused as internal."""
    key = ("identity.login", "account", "opaque:account")
    return [
        ("state-dict-subclass", _DictSub({})),
        ("state-list", []),
        ("state-key-str", {"identity.login": (0, 1)}),
        ("state-key-short-tuple", {("identity.login", "account"): (0, 1)}),
        ("state-value-list", {key: [0, 1]}),
        ("state-value-short-tuple", {key: (0,)}),
        ("state-value-str", {key: "0,1"}),
    ]


_FIELD_PROBES = _field_probes()
_STATE_PROBES = _state_probes()


def _run_field_probe(probe):
    label, call, code = probe
    _run_refusal_call(call, code, f"probe:{label}")


def _run_state_probe(probe):
    label, hostile_state = probe
    _run_refusal_call(_probe_base(), "internal", f"probe:{label}", ref_state=hostile_state)


def test_opaque_key_lone_surrogate_is_a_declared_gap():
    """The synthetic model admits any opaque:-prefixed str as a key, including
    bytes a real normalizer would never emit (contract unresolved
    account_normalization/source_normalization keep normalizers out of
    scope). Pinned as declared behavior, not a production choice."""
    call = _probe_base()
    call["account"] = "opaque:\ud800"
    _run_verdict_call(
        call,
        {
            "outcome": "admit",
            "state": [
                {
                    "operation": "identity.login",
                    "scope": "account",
                    "opaque": "opaque:\ud800",
                    "window": 0,
                    "count": 1,
                },
                {
                    "operation": "identity.login",
                    "scope": "source",
                    "opaque": "opaque:source",
                    "window": 0,
                    "count": 1,
                },
            ],
        },
        "probe:opaque-key-lone-surrogate",
    )


def test_replay_branch_skips_request_policy_state_and_store_validation():
    """Declared in the fixture notes: with a boolean body_same the replay
    branch replays or conflicts without request, policy, state or store
    validation. Pinned here with every one of those inputs hostile."""
    hostile = {
        "operation": object(),
        "account": object(),
        "source": object(),
        "now": -1,
        "policy": None,
        "store_available": False,
        "effect_ok": False,
    }
    corrupt_state = {("identity.login", "account", "opaque:account"): (0, -1)}
    corrupt_records = [
        {
            "operation": "identity.login",
            "scope": "account",
            "opaque": "opaque:account",
            "window": 0,
            "count": -1,
        }
    ]
    call = _probe_base()
    call.update(replay="cached", body_same=True, **hostile)
    _run_verdict_call(
        call,
        {"outcome": "replay", "state": corrupt_records},
        "probe:replay-skips-validation",
        ref_state=corrupt_state,
    )
    conflict = _probe_base()
    conflict.update(replay="cached", body_same=False, **hostile)
    _run_refusal_call(
        conflict,
        "idempotency_conflict",
        "probe:replay-skips-validation-conflict",
        ref_state=corrupt_state,
    )


@pytest.mark.parametrize("label", [label for label, _, _ in _FIELD_PROBES])
def test_derived_field_probes_refuse_typed(label):
    (probe,) = [probe for probe in _FIELD_PROBES if probe[0] == label]
    _run_field_probe(probe)


@pytest.mark.parametrize("label", [label for label, _ in _STATE_PROBES])
def test_derived_state_probes_refuse_typed(label):
    (probe,) = [probe for probe in _STATE_PROBES if probe[0] == label]
    _run_state_probe(probe)


# -- mutant battery ---------------------------------------------------------------


def _fixture_red():
    """Labels of executed fixture checks that disagree with the reference
    currently bound; empty when green. Every label comes from a row or probe
    executed through decision(): no source-text or table-shape check counts."""
    red = []
    for section in VERDICT_SECTIONS:
        for row in CASES[section]:
            try:
                _run_verdict_row(row, f"{section}:{row['name']}")
            except BaseException:  # noqa: BLE001
                red.append(f"{section}:{row['name']}")
    for row in CASES["malformed"]:
        try:
            _run_refusal_row(row, f"malformed:{row['name']}")
        except BaseException:  # noqa: BLE001
            red.append(f"malformed:{row['name']}")
    for row in CASES["rollback"]:
        try:
            _run_rollback_row(row)
        except BaseException:  # noqa: BLE001
            red.append(f"rollback:{row['name']}")
    for probe in _FIELD_PROBES:
        try:
            _run_field_probe(probe)
        except BaseException:  # noqa: BLE001
            red.append(f"probe:{probe[0]}")
    for probe in _STATE_PROBES:
        try:
            _run_state_probe(probe)
        except BaseException:  # noqa: BLE001
            red.append(f"probe:{probe[0]}")
    try:
        test_opaque_key_lone_surrogate_is_a_declared_gap()
    except BaseException:  # noqa: BLE001
        red.append("probe:opaque-key-lone-surrogate")
    try:
        test_replay_branch_skips_request_policy_state_and_store_validation()
    except BaseException:  # noqa: BLE001
        red.append("probe:replay-skips-validation")
    return red


# Source-level mutants of the T0455 synthetic reference. Each edit is a
# single, minimal behavioral defect; every one must turn executed fixture
# rows red.
REFERENCE_MUTANTS = {
    "capacity-off-by-one-admit": (
        'if active >= cfg["capacity"]:',
        'if active > cfg["capacity"]:',
        "over-admit one past capacity",
    ),
    "capacity-off-by-one-deny": (
        'if active >= cfg["capacity"]:',
        'if active >= cfg["capacity"] - 1:',
        "deny one below capacity",
    ),
    "old-window-count-carried": (
        "active = count if old_window == window else 0",
        "active = count",
        "old window counts carry",
    ),
    "window-floor-shifted": (
        'window = now // cfg["window_ms"]',
        'window = (now + 1) // cfg["window_ms"]',
        "window floor shifted one tick",
    ),
    "account-bucket-unchecked": (
        'for label, opaque in (("account", account), ("source", source)):',
        'for label, opaque in (("source", source),):',
        "account bucket never consulted",
    ),
    "source-bucket-unchecked": (
        'for label, opaque in (("account", account), ("source", source)):',
        'for label, opaque in (("account", account),):',
        "source bucket never consulted",
    ),
    "deny-increments-caller-state": (
        "pending[key] = (window, active + 1)",
        "state[key] = (window, active + 1)\n        pending[key] = (window, active + 1)",
        "denial leaks the first bucket into caller state",
    ),
    "admit-does-not-increment": (
        "pending[key] = (window, active + 1)",
        "pending[key] = (window, active)",
        "admission consumes no slot",
    ),
    "replay-refused-as-malformed": (
        'if replay == "cached" and body_same:',
        'if replay == "cached" and body_same and False:',
        "cached replay never replays",
    ),
    "conflict-replays": (
        'if replay == "cached" and body_same:',
        'if replay == "cached":',
        "conflicting replay replays",
    ),
    "conflict-token-unchecked": (
        'if replay == "cached" and not body_same:',
        'if replay == "cached" and not body_same and False:',
        "conflict misclassified as malformed",
    ),
    "store-outage-ignored": (
        "if not store_available:",
        "if store_available is None:",
        "store outage admits",
    ),
    "effect-failure-ignored": (
        "if not effect_ok:",
        "if effect_ok is None:",
        "transaction failure reports success",
    ),
    "raw-account-accepted": (
        '        or not account.startswith("opaque:")\n',
        "",
        "raw account identifier accepted",
    ),
    "raw-source-accepted": (
        '        or not source.startswith("opaque:")\n',
        "",
        "raw source identifier accepted",
    ),
    "now-bool-accepted": (
        "or type(now) is not int",
        "or type(now) not in (int, bool)",
        "bool accepted as the clock",
    ),
    "now-negative-accepted": (
        "or not 0 <= now <= MAX_CLOCK",
        "or not -1 <= now <= MAX_CLOCK",
        "negative clock accepted",
    ),
    "now-past-max-accepted": (
        "or not 0 <= now <= MAX_CLOCK",
        "or not 0 <= now <= MAX_CLOCK + 1",
        "clock past 2**53-1 accepted",
    ),
    "capacity-zero-accepted": (
        "or not 1 <= cfg[k] <= MAX_CLOCK",
        "or not 0 <= cfg[k] <= MAX_CLOCK",
        "zero capacity or window accepted",
    ),
    "policy-version-zero-accepted": (
        'or policy["version"] < 1',
        'or policy["version"] < 0',
        "policy version zero accepted",
    ),
    "policy-version-bool-accepted": (
        'or type(policy["version"]) is not int',
        'or type(policy["version"]) not in (int, bool)',
        "bool policy version accepted",
    ),
    "operation-check-dropped": (
        "        or operation not in OPS\n",
        "",
        "undeclared operation admitted",
    ),
    "operation-scope-shared": (
        "key = (operation, label, opaque)",
        'key = ("identity.login", label, opaque)',
        "operations share buckets",
    ),
    "new-state-aliased": (
        "new_state = copy.deepcopy(state)",
        "new_state = state",
        "admitted state aliases the caller's",
    ),
    "replay-state-aliased": (
        'return "replay", copy.deepcopy(state)',
        'return "replay", state',
        "replayed state aliases the caller's",
    ),
    "corrupt-state-values-accepted": (
        "or any(type(n) is not int or n < 0 for n in v)",
        "or any(type(n) is not int and n < 0 for n in v)",
        "corrupt stored counts accepted",
    ),
    "corrupt-state-keys-accepted": (
        "type(k) is not tuple\n        or len(k) != 3",
        "type(k) is not tuple and type(k) is not str\n        or len(k) != 3 and type(k) is tuple",
        "corrupt stored keys accepted",
    ),
    "regression-ignored": (
        'if old_window > window or (old_window == window and count > cfg["capacity"]):',
        'if old_window > window and count > cfg["capacity"]:',
        "regressed or over-capacity store accepted",
    ),
}

# Edits that must NOT change behavior on any executed row.
EQUIVALENT_EDITS = {
    "bucket-loop-order": (
        '(("account", account), ("source", source))',
        '(("source", source), ("account", account))',
    ),
    "replay-condition-swapped": (
        'if replay == "cached" and body_same:',
        'if body_same and replay == "cached":',
    ),
    "increment-form": (
        "pending[key] = (window, active + 1)",
        "pending[key] = (window, 1 + active)",
    ),
    "window-equality-expanded": (
        "active = count if old_window == window else 0",
        "active = count if old_window >= window else 0",
    ),
}


def _rebind(before, after, name):
    source = inspect.getsource(_REF.decision)
    assert source.count(before) == 1, name
    scope = dict(vars(_REF))
    exec(  # noqa: S102
        compile(ast.parse(source.replace(before, after, 1)), f"<rate-limit:{name}>", "exec"),
        scope,
    )
    return scope["decision"]


def test_reference_edits_apply():
    for name, (before, after, _why) in REFERENCE_MUTANTS.items():
        mutant = _rebind(before, after, name)
        assert mutant is not _REF.decision
    for name, (before, after) in EQUIVALENT_EDITS.items():
        _rebind(before, after, name)


def test_reference_is_green():
    assert _fixture_red() == []


@pytest.mark.parametrize("name", sorted(REFERENCE_MUTANTS))
def test_reference_mutants_turn_the_fixture_red(name, monkeypatch):
    before, after, _why = REFERENCE_MUTANTS[name]
    monkeypatch.setattr(_REF, "decision", _rebind(before, after, name))
    assert _fixture_red() != [], name


@pytest.mark.parametrize("name", sorted(EQUIVALENT_EDITS))
def test_equivalent_edits_keep_the_fixture_green(name, monkeypatch):
    before, after = EQUIVALENT_EDITS[name]
    monkeypatch.setattr(_REF, "decision", _rebind(before, after, name))
    assert _fixture_red() == [], name
