"""T0429: closed, executable fixture for the v1 control-plane event contract.

The corpus (tests/fixtures/control-plane-events/cases.json, generated by
tools/events_fixture_generate.py) exercises the T0428 reference battery's
public boundaries - validate() and Ledger.publish() - with pinned happy,
boundary, malformed and rollback rows; hostile-type probes derived from
every accepted row; and a mutant battery whose kills all come from executed
fixture rows, never source-text checks.
"""

from __future__ import annotations

import ast
import copy
import hashlib
import inspect
import json
import tempfile
import unittest.mock
from pathlib import Path

import pytest
import yaml

import tests.test_t0428_events_contract as _REF
import tools.events_fixture_generate as _GEN
from tools.events_contract_lint import CONTRACT, SOURCE
from tools.events_contract_lint import lint as contract_lint
from tools.variant_contract_lint import ContractError

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "control-plane-events" / "cases.json"
CASES = json.loads(FIXTURE.read_text())
CONTRACT_DOC = yaml.safe_load(CONTRACT.read_text())["contract"]
SOURCE_DOC = yaml.safe_load(SOURCE.read_text())
CATALOG = list(CONTRACT_DOC["catalog"]["operation_ids"])
OPERATIONS = {
    f"{area}.{op}": spec["errors"]
    for area, detail in SOURCE_DOC["areas"].items()
    for op, spec in detail["ops"].items()
}
FAILURE_CLASSES = set(CONTRACT_DOC["failure"]["classes"])
FIELDS = list(CONTRACT_DOC["envelope"]["fields"])
REQUIRED = [field for field in FIELDS if field != "error_code"]
SECTIONS = ("happy", "boundary", "malformed", "rollback")
TOP_KEYS = {
    "schema_version",
    "contract",
    "contract_schema_version",
    "notes",
    "section_manifests",
    *SECTIONS,
}
CASE_KEYS = {
    "happy": {"name", "event"},
    "boundary": {"name", "event"},
    "malformed": {"name", "why", "event", "expect_failure", "minimal_repair"},
    "rollback": {
        "name",
        "why",
        "published",
        "batch",
        "inject_fault",
        "restart",
        "expect_failure",
        "expect_published",
        "follow_up",
        "expect_after_follow_up",
    },
}
MAX_OCCURRED_AT = 253402300799999
IDENTIFIER_CHARS = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")
SECRETS = (
    "1. e4 e5 2. Nf3 Nc6",
    "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
    '[Event "x"] 1. d4 d5 1-0',
    "sk-live-9f8e7d6c5b4a-fixture",
    "hunter2-fixture",
    "user@example.com",
)


# -- late-bound reference access (reference mutants rebind these) ------------


def _validate(event):
    return _REF.validate(event)


def _new_ledger():
    return _REF.Ledger()


def _publish(ledger, batch, *, fail_commit=False):
    return ledger.publish(batch, fail_commit=fail_commit)


# -- snapshots and detachment -------------------------------------------------


def _containers_of(*roots):
    seen, out, stack = set(), [], list(reversed(roots))
    while stack:
        node = stack.pop()
        if isinstance(node, (dict, list)) and id(node) not in seen:
            seen.add(id(node))
            out.append(node)
            stack.extend(dict.values(node) if isinstance(node, dict) else list.__iter__(node))
    return out


def _snap_key(key):
    return str.__str__(key) if isinstance(key, str) else (type(key).__name__, repr(type(key)))


def _snap(obj, _seen=None):
    """Type-exact snapshot; aliases and cycles snapshot as references."""
    seen = {} if _seen is None else _seen
    if isinstance(obj, (dict, list)):
        if id(obj) in seen:
            return ("ref", seen[id(obj)])
        seen[id(obj)] = len(seen)
        if isinstance(obj, dict):
            body = [(type(obj).__name__, _snap_key(k), _snap(v, seen)) for k, v in dict.items(obj)]
        else:
            body = [_snap(v, seen) for v in list.__iter__(obj)]
        return (type(obj).__name__, body)
    if isinstance(obj, str):
        return (type(obj).__name__, str.__str__(obj))
    return (type(obj).__name__, obj)


# -- fixture structure and closure --------------------------------------------


def _canon(case):
    return json.dumps(case, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def _check_event_shape(event, where):
    assert type(event) is dict, where
    assert set(event) - set(FIELDS) == set(), where
    assert set(REQUIRED) - set(event) == set(), where
    assert type(event["version"]) is int and event["version"] == 1, where
    assert event["operation_id"] in CATALOG, where
    assert event["outcome"] in ("succeeded", "failed"), where
    assert event["name"] == f"control_plane.{event['operation_id']}.{event['outcome']}", where
    for key in ("event_id", "correlation_id"):
        value = event[key]
        assert type(value) is str and 1 <= len(value) <= 64, where
        assert set(value) <= IDENTIFIER_CHARS, where
    assert type(event["occurred_at"]) is int and 0 <= event["occurred_at"] <= MAX_OCCURRED_AT, where
    if event["outcome"] == "failed":
        assert event["error_code"] in OPERATIONS[event["operation_id"]], where
    else:
        assert "error_code" not in event, where


def _check(cases):
    assert type(cases) is dict
    assert set(cases) == TOP_KEYS, f"top keys {sorted(cases)}"
    assert type(cases["schema_version"]) is int and cases["schema_version"] == 1
    assert cases["contract"] == "data/contracts/events.yaml"
    contract_doc = yaml.safe_load((ROOT / cases["contract"]).read_text())
    assert cases["contract_schema_version"] == contract_doc["schema_version"]
    assert type(cases["notes"]) is str and "synthetic" in cases["notes"]
    assert "provenance" in cases["notes"]
    assert set(cases["section_manifests"]) == set(SECTIONS)
    names = []
    for section in SECTIONS:
        rows = cases[section]
        assert type(rows) is list and rows, section
        manifest = cases["section_manifests"][section]
        assert type(manifest) is dict
        assert list(manifest) == [row["name"] for row in rows], section
        computed = {row["name"]: hashlib.sha256(_canon(row)).hexdigest() for row in rows}
        assert manifest == computed, section
        for row in rows:
            where = f"{section}:{row.get('name')}"
            assert set(row) == CASE_KEYS[section], where
            assert type(row["name"]) is str and row["name"], where
            names.append(row["name"])
        if section in ("happy", "boundary"):
            for row in rows:
                _check_event_shape(row["event"], f"{section}:{row['name']}")
        elif section == "malformed":
            for row in rows:
                assert row["expect_failure"] in FAILURE_CLASSES, row["name"]
                assert type(row["why"]) is str and row["why"], row["name"]
                _check_event_shape(row["minimal_repair"], f"malformed:{row['name']}:repair")
        else:
            for row in rows:
                where = f"rollback:{row['name']}"
                assert type(row["why"]) is str and row["why"], where
                assert type(row["inject_fault"]) is bool, where
                assert type(row["restart"]) is bool, where
                failure = row["expect_failure"]
                assert failure is None or failure in FAILURE_CLASSES, where
                assert type(row["expect_published"]) is int, where
                assert type(row["expect_after_follow_up"]) is int, where
                for key in ("published", "batch", "follow_up"):
                    assert type(row[key]) is list, where
                for batch in row["published"]:
                    assert type(batch) is list
                    for event in batch:
                        _check_event_shape(event, where)
                for event in row["follow_up"]:
                    _check_event_shape(event, where)
    assert len(names) == len(set(names))
    expected = {f"{op}-succeeded" for op in CATALOG}
    expected |= {f"{op}-failed-{code}" for op in CATALOG for code in OPERATIONS[op]}
    assert {row["name"] for row in cases["happy"]} == expected


def test_fixture_structure():
    _check(CASES)


def test_fixture_matches_generator():
    assert _GEN.dump(_GEN.build()) == FIXTURE.read_text()


@pytest.mark.parametrize("section", SECTIONS)
def test_closed_manifest_detects_reorder_drop_and_extra(section):
    manifest = CASES["section_manifests"][section]
    names = [row["name"] for row in CASES[section]]
    assert list(manifest) == names
    assert len(names) == len(set(names))


def _check_section(cases, section):
    """The manifest closure for one section: digests, order, key shapes."""
    rows = cases[section]
    assert type(rows) is list and rows, section
    manifest = cases["section_manifests"][section]
    assert list(manifest) == [row["name"] for row in rows], section
    computed = {row["name"]: hashlib.sha256(_canon(row)).hexdigest() for row in rows}
    assert manifest == computed, section
    for row in rows:
        assert set(row) == CASE_KEYS[section], f"{section}:{row.get('name')}"


def test_row_substitution_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                mutant_rows = copy.deepcopy(rows)
                replacement = copy.deepcopy(mutant_rows[donor])
                replacement["name"] = mutant_rows[target]["name"]
                mutant_rows[target] = replacement
                mutant = {**CASES, section: mutant_rows}
                with pytest.raises(AssertionError):
                    _check_section(mutant, section)


def test_each_row_field_is_manifest_bound():
    for section in SECTIONS:
        rows = CASES[section]
        for target in range(len(rows)):
            for donor in range(len(rows)):
                if target == donor:
                    continue
                shared = (set(rows[target]) & set(rows[donor])) - {"name"}
                for field in shared:
                    if rows[target][field] == rows[donor][field]:
                        continue
                    mutant_rows = copy.deepcopy(rows)
                    mutant_rows[target][field] = copy.deepcopy(rows[donor][field])
                    mutant = {**CASES, section: mutant_rows}
                    with pytest.raises(AssertionError):
                        _check_section(mutant, section)


def test_structure_mutations_fail():
    for bad in (True, 1.0, "1", 0, 2):
        mutant = copy.deepcopy(CASES)
        mutant["schema_version"] = bad
        with pytest.raises(AssertionError):
            _check(mutant)
    for section in SECTIONS:
        mutant = copy.deepcopy(CASES)
        mutant[section][0]["rogue"] = None
        with pytest.raises(AssertionError):
            _check(mutant)
    mutant = copy.deepcopy(CASES)
    mutant["rogue_section"] = []
    with pytest.raises(AssertionError):
        _check(mutant)


# -- executed rows --------------------------------------------------------------


def _restart(ledger):
    """A fresh ledger restored from the persisted event sequence."""
    events = json.loads(json.dumps(ledger.events))
    fresh = _new_ledger()
    fresh.events = events
    fresh.seen = {event["event_id"]: event for event in events}
    return fresh


def _assert_detached(ledger, inputs):
    held = {id(node) for node in _containers_of(*inputs)}
    for committed in ledger.events:
        shared = [node for node in _containers_of(committed) if id(node) in held]
        assert shared == [], "the committed ledger shares a container with the caller's inputs"


def _run_accepted(event):
    ledger = _new_ledger()
    attempt = copy.deepcopy(event)
    assert _publish(ledger, [attempt]) == 1
    assert ledger.events == [event]
    assert _snap(ledger.events[0]) == _snap(event)
    _assert_detached(ledger, [attempt])
    # identical replay is a no-op, in-process and across a restart
    assert _publish(ledger, [copy.deepcopy(event)]) == 1
    assert ledger.events == [event]
    restored = _restart(ledger)
    assert _publish(restored, [copy.deepcopy(event)]) == 1
    assert restored.events == [event]


@pytest.mark.parametrize("section", ("happy", "boundary"))
def test_accepted_rows_execute_and_replay(section):
    for row in CASES[section]:
        _run_accepted(row["event"])


def test_happy_section_covers_every_operation_and_declared_error():
    rows = CASES["happy"]
    by_op = {}
    for op in CATALOG:
        succeeded = [row for row in rows if row["name"] == f"{op}-succeeded"]
        assert len(succeeded) == 1, op
        failed = {
            row["event"]["error_code"]
            for row in rows
            if row["name"].startswith(f"{op}-failed-")
        }
        assert failed == set(OPERATIONS[op]), op
        by_op[op] = failed
    assert len(rows) == len(CATALOG) + sum(len(codes) for codes in OPERATIONS.values())


def _malformed_names():
    return [row["name"] for row in CASES["malformed"]]


@pytest.mark.parametrize("name", _malformed_names())
def test_malformed_row_refused_typed_without_echo_or_side_effect(name):
    (row,) = [row for row in CASES["malformed"] if row["name"] == name]
    event = row["event"]
    before = _snap(event)
    with pytest.raises(_REF.Refusal) as raised:
        _validate(event)
    assert type(raised.value) is _REF.Refusal
    assert raised.value.failure_class == row["expect_failure"]
    for secret in SECRETS:
        assert secret not in str(raised.value)
        assert secret not in repr(raised.value)
    assert _snap(event) == before
    # the same row inside a batch refuses the whole batch: no partial ledger
    valid = copy.deepcopy(CASES["happy"][0]["event"])
    ledger = _new_ledger()
    batch = [valid, copy.deepcopy(event)]
    with pytest.raises(_REF.Refusal) as raised:
        _publish(ledger, batch)
    assert raised.value.failure_class == row["expect_failure"]
    assert ledger.events == [] and ledger.seen == {}
    assert _snap(batch[1]) == before


@pytest.mark.parametrize("name", _malformed_names())
def test_malformed_minimal_repair_executes(name):
    (row,) = [row for row in CASES["malformed"] if row["name"] == name]
    _run_accepted(row["minimal_repair"])


def _rollback_names():
    return [row["name"] for row in CASES["rollback"]]


@pytest.mark.parametrize("name", _rollback_names())
def test_rollback_row(name):
    (row,) = [row for row in CASES["rollback"] if row["name"] == name]
    ledger = _new_ledger()
    for batch in row["published"]:
        attempt = copy.deepcopy(batch)
        _publish(ledger, attempt)
    assert len(ledger.events) == sum(
        len({event["event_id"] for event in batch}) for batch in row["published"]
    )
    if row["restart"]:
        ledger = _restart(ledger)
    before_events = copy.deepcopy(ledger.events)
    attempt = copy.deepcopy(row["batch"])
    attempt_snap = _snap(attempt)
    if row["expect_failure"] is None:
        assert _publish(ledger, attempt, fail_commit=row["inject_fault"]) == row["expect_published"]
    else:
        with pytest.raises(_REF.Refusal) as raised:
            _publish(ledger, attempt, fail_commit=row["inject_fault"])
        assert type(raised.value) is _REF.Refusal
        assert raised.value.failure_class == row["expect_failure"]
        assert ledger.events == before_events, "a refused batch left a partial publication"
    assert len(ledger.events) == row["expect_published"]
    assert _snap(attempt) == attempt_snap, "the refused/published attempt mutated its inputs"
    _assert_detached(ledger, [attempt])
    follow = copy.deepcopy(row["follow_up"])
    assert _publish(ledger, follow) == row["expect_after_follow_up"]
    _assert_detached(ledger, [follow])


# -- hostile types (logged: any call is a failure) ------------------------------

HOSTILE = []


class _Armed:
    on = False


def _log(name):
    if _Armed.on:
        HOSTILE.append(name)


class _StrSub(str):
    pass


class _IntSub(int):
    pass


class _FloatSub(float):
    pass


class _DictSub(dict):
    pass


class _ListSub(list):
    pass


class _TupleBatch(tuple):
    pass


class _LyingDict(dict):
    def __getitem__(self, key):
        _log("getitem")
        return dict.__getitem__(self, key)

    def __iter__(self):
        _log("iter")
        return dict.__iter__(self)

    def __len__(self):
        _log("len")
        return dict.__len__(self)

    def keys(self):
        _log("keys")
        return dict.keys(self)

    def items(self):
        _log("items")
        return dict.items(self)

    def get(self, key, default=None):
        _log("get")
        return dict.get(self, key, default)


class _EqRaises(str):
    def __eq__(self, other):
        _log("eq")
        raise RuntimeError("hostile __eq__")

    def __hash__(self):
        _log("hash")
        return str.__hash__(self)


class _NonStrKey:
    """Hashes like the real key and raises on comparison."""

    def __init__(self, name):
        self.name = name

    def __hash__(self):
        _log("hash")
        return hash(self.name)

    def __eq__(self, other):
        _log("eq")
        raise RuntimeError("hostile __eq__")


class _ReprRaises(str):
    def __repr__(self):
        _log("repr")
        raise RuntimeError("hostile __repr__")

    def __str__(self):
        _log("str")
        raise RuntimeError("hostile __str__")

    def __format__(self, spec):
        _log("format")
        raise RuntimeError("hostile __format__")


class _GeneratorBatch:
    def __iter__(self):
        _log("iter")
        raise RuntimeError("hostile __iter__")


_STR_FIELDS = ("name", "operation_id", "event_id", "correlation_id", "outcome", "error_code")
_INT_FIELDS = ("version", "occurred_at")


def _rekey(mapping, field, make):
    return {(make(k) if k == field else k): v for k, v in mapping.items()}


def _event_variants(event):
    """(label, hostile event, expected failure class) for one accepted event."""
    out = [
        ("container-dict-subclass", _DictSub(event), "malformed_event"),
        ("container-lying-dict", _LyingDict(event), "malformed_event"),
        ("event-none", None, "malformed_event"),
        ("event-int", 7, "malformed_event"),
        ("event-string", "control_plane.x.succeeded", "malformed_event"),
        ("event-list-field-names", sorted(event), "malformed_event"),
    ]
    for field in event:
        out.append((f"key-str-subclass:{field}", _rekey(event, field, _StrSub), "malformed_event"))
        out.append((f"key-eq-raises:{field}", _rekey(event, field, _EqRaises), "malformed_event"))
        out.append((f"key-non-str:{field}", _rekey(event, field, _NonStrKey), "malformed_event"))
    for field in _STR_FIELDS:
        if field not in event:
            continue
        expected = "unknown_name" if field in ("name", "operation_id") else "malformed_event"
        out.append(
            (f"value-str-subclass:{field}", {**event, field: _StrSub(event[field])}, expected)
        )
        out.append(
            (f"value-eq-raises:{field}", {**event, field: _EqRaises(event[field])}, expected)
        )
        out.append(
            (f"value-repr-raises:{field}", {**event, field: _ReprRaises(event[field])}, expected)
        )
    for field in _INT_FIELDS:
        value = event[field]
        out.append(
            (f"value-int-subclass:{field}", {**event, field: _IntSub(value)}, "malformed_event")
        )
        out.append((f"value-bool:{field}", {**event, field: True}, "malformed_event"))
        out.append((f"value-float:{field}", {**event, field: float(value)}, "malformed_event"))
        out.append(
            (f"value-float-subclass:{field}", {**event, field: _FloatSub(value)}, "malformed_event")
        )
        out.append((f"value-str:{field}", {**event, field: str(value)}, "malformed_event"))
    return out


def _batch_variants(event):
    return [
        ("batch-list-subclass", _ListSub([event])),
        ("batch-tuple", tuple([event])),
        ("batch-dict", {"event": event}),
        ("batch-none", None),
        ("batch-string", "batch"),
        ("batch-generator", _GeneratorBatch()),
    ]


def _expect_typed_refusal(call, failure_class, watched, ledger=None):
    snaps = [_snap(item) for item in watched]
    HOSTILE.clear()
    _Armed.on = True
    try:
        try:
            call()
            got = "accepted"
        except _REF.Refusal as exc:
            got = (type(exc) is _REF.Refusal, exc.failure_class)
        except BaseException as exc:  # noqa: BLE001 - a raw escape is the failure
            got = ("raw", type(exc).__name__)
        calls = list(HOSTILE)
    finally:
        _Armed.on = False
    assert got == (True, failure_class), got
    assert calls == [], calls
    assert [_snap(item) for item in watched] == snaps, "hostile input was mutated"
    if ledger is not None:
        assert ledger.events == [] and ledger.seen == {}, "hostile input left a partial ledger"


def _hostile_event(event, label, hostile, failure_class):
    try:
        _expect_typed_refusal(lambda: _validate(hostile), failure_class, [hostile])
        ledger = _new_ledger()
        _expect_typed_refusal(
            lambda: _publish(ledger, [hostile]), failure_class, [hostile], ledger=ledger
        )
    except AssertionError as exc:
        raise AssertionError(f"{label}: {exc}") from None


def _hostile_batch(label, batch):
    try:
        ledger = _new_ledger()
        _expect_typed_refusal(lambda: _publish(ledger, batch), "malformed_event", [batch], ledger)
    except AssertionError as exc:
        raise AssertionError(f"{label}: {exc}") from None


_ACCEPTED = [
    (f"{section}:{row['name']}", row["event"])
    for section in ("happy", "boundary")
    for row in CASES[section]
]


@pytest.mark.parametrize("label", [label for label, _ in _ACCEPTED])
def test_hostile_variants_of_every_accepted_row(label):
    (event,) = [event for row_label, event in _ACCEPTED if row_label == label]
    _run_accepted(copy.deepcopy(event))  # the base input is genuinely accepted
    for variant_label, hostile, failure_class in _event_variants(event):
        _hostile_event(event, f"{variant_label}", hostile, failure_class)
    for batch_label, batch in _batch_variants(copy.deepcopy(event)):
        _hostile_batch(batch_label, batch)


def test_hostile_variant_set_is_complete():
    for _, event in _ACCEPTED:
        labels = [label for label, _, _ in _event_variants(event)]
        assert len(labels) == len(set(labels))
        str_fields = [field for field in _STR_FIELDS if field in event]
        assert len(labels) == 6 + 3 * len(event) + 3 * len(str_fields) + 5 * len(_INT_FIELDS)
    assert len(_batch_variants(CASES["happy"][0]["event"])) == 6


# -- the catalog baseline pin cannot be bypassed by a joint edit ----------------


def test_catalog_baseline_pin_survives_joint_source_and_catalog_edit():
    source = copy.deepcopy(SOURCE_DOC)
    operation = copy.deepcopy(source["areas"]["identity"]["ops"]["refresh"])
    operation["path"] = "/identity/restore"
    source["areas"]["identity"]["ops"]["restore"] = operation
    contract = yaml.safe_load(CONTRACT.read_text())
    ids = sorted(contract["contract"]["catalog"]["operation_ids"] + ["identity.restore"])
    contract["contract"]["catalog"]["operation_ids"] = ids
    # even a self-consistent digest update cannot bless the joint edit: the
    # v1 baseline is pinned in the lint itself
    contract["contract"]["catalog"]["baseline_sha256"] = hashlib.sha256(
        "\n".join(ids).encode("ascii")
    ).hexdigest()
    original = yaml.safe_load

    def injected(stream):
        parsed = original(stream)
        return source if parsed == SOURCE_DOC else parsed

    with tempfile.TemporaryDirectory() as temporary:
        path = Path(temporary) / "joint-mutant.yaml"
        path.write_text(yaml.safe_dump(contract))
        with (
            unittest.mock.patch("tools.events_contract_lint.yaml.safe_load", side_effect=injected),
            pytest.raises(ContractError, match="catalog baseline"),
        ):
            contract_lint(path)
    # and the would-be operation stays refused at the event boundary
    (row,) = [row for row in CASES["malformed"] if row["name"] == "operation-unknown"]
    with pytest.raises(_REF.Refusal) as raised:
        _validate(row["event"])
    assert raised.value.failure_class == "unknown_name"


# -- reference mutants: each must turn the executed fixture rows red ------------

REFERENCE_EDITS = {
    "event-container-off": (
        "    if type(event) is not dict:\n        raise Refusal(\"malformed_event\")",
        "    if event is None:\n        raise Refusal(\"malformed_event\")",
    ),
    "key-type-guard-off": (
        "    if any(type(key) is not str for key in event):\n"
        "        raise Refusal(\"malformed_event\")\n",
        "",
    ),
    "undeclared-field-ok": (
        "    if set(event) - FIELDS or FIELDS - {\"error_code\"} - set(event):",
        "    if FIELDS - {\"error_code\"} - set(event):",
    ),
    "missing-field-ok": (
        "    if set(event) - FIELDS or FIELDS - {\"error_code\"} - set(event):",
        "    if set(event) - FIELDS:",
    ),
    "version-isinstance": (
        "    if type(event[\"version\"]) is not int:",
        "    if not isinstance(event[\"version\"], int):",
    ),
    "version-two-ok": (
        "    if event[\"version\"] != 1:",
        "    if event[\"version\"] not in (1, 2):",
    ),
    "operation-any-string": (
        "    if type(event[\"operation_id\"]) is not str"
        " or event[\"operation_id\"] not in OPERATIONS:",
        "    if type(event[\"operation_id\"]) is not str:",
    ),
    "outcome-queued-ok": (
        "(\"succeeded\", \"failed\")",
        "(\"succeeded\", \"failed\", \"queued\")",
    ),
    "name-check-off": (
        "    if type(event[\"name\"]) is not str or event[\"name\"] != name:",
        "    if type(event[\"name\"]) is not str:",
    ),
    "identifier-second-field-off": (
        "for key in (\"event_id\", \"correlation_id\"):",
        "for key in (\"event_id\",):",
    ),
    "identifier-type-off": (
        "        if type(event[key]) is not str or IDENTIFIER.fullmatch(event[key]) is None:",
        "        if IDENTIFIER.fullmatch(event[key]) is None:",
    ),
    "occurred-at-isinstance": (
        "    if type(event[\"occurred_at\"]) is not int"
        " or not 0 <= event[\"occurred_at\"] <= 253402300799999:",
        "    if not isinstance(event[\"occurred_at\"], int)"
        " or not 0 <= event[\"occurred_at\"] <= 253402300799999:",
    ),
    "occurred-at-ceiling-plus": ("253402300799999", "253402300800000"),
    "occurred-at-floor-minus": (
        "not 0 <= event[\"occurred_at\"]",
        "not -1 <= event[\"occurred_at\"]",
    ),
    "error-code-any-string": (
        "            or event[\"error_code\"] not in OPERATIONS[event[\"operation_id\"]]",
        "            or not event[\"error_code\"]",
    ),
    "error-code-optional-on-failed": (
        "        if (\n"
        "            type(event.get(\"error_code\")) is not str\n"
        "            or event[\"error_code\"] not in OPERATIONS[event[\"operation_id\"]]\n"
        "        ):",
        "        if event.get(\"error_code\") is not None and (\n"
        "            type(event.get(\"error_code\")) is not str\n"
        "            or event[\"error_code\"] not in OPERATIONS[event[\"operation_id\"]]\n"
        "        ):",
    ),
    "error-code-on-success-ok": ("    elif \"error_code\" in event:", "    elif False:"),
    "validate-not-called": (
        "        proposed = [validate(e) for e in batch]",
        "        proposed = [copy.deepcopy(e) for e in batch]",
    ),
    "conflict-check-off": (
        "            if (\n"
        "                key in self.seen\n"
        "                and self.seen[key] != event\n"
        "                or key in staged\n"
        "                and staged[key] != event\n"
        "            ):",
        "            if False:",
    ),
    "conflict-class-wrong": (
        "raise Refusal(\"duplicate_conflict\")",
        "raise Refusal(\"malformed_event\")",
    ),
    "unknown-name-class-wrong": (
        "raise Refusal(\"unknown_name\")",
        "raise Refusal(\"malformed_event\")",
    ),
    "replay-appends-duplicate": (
        "            if event[\"event_id\"] not in self.seen:",
        "            if True:",
    ),
    "publication-fault-ignored": (
        "        if fail_commit:\n            raise Refusal(\"publication_failure\")\n",
        "",
    ),
    "publication-class-wrong": (
        "raise Refusal(\"publication_failure\")",
        "raise Refusal(\"internal\")",
    ),
    "no-deepcopy": ("    return copy.deepcopy(event)", "    return event"),
    "batch-type-off": (
        "        if type(batch) is not list:",
        "        if batch is None:",
    ),
}

# edits that must NOT change behavior
EQUIVALENT_EDITS = {
    "outcome-tuple-order": (
        "(\"succeeded\", \"failed\")",
        "(\"failed\", \"succeeded\")",
    ),
    "identifier-loop-order": (
        "(\"event_id\", \"correlation_id\")",
        "(\"correlation_id\", \"event_id\")",
    ),
    "key-guard-all-form": (
        "any(type(key) is not str for key in event)",
        "not all(type(key) is str for key in event)",
    ),
}


def _reference_block():
    source = inspect.getsource(_REF)
    tree = ast.parse(source)
    spans = []
    for node in tree.body:
        if (
            isinstance(node, ast.ClassDef)
            and node.name in ("Refusal", "Ledger")
            or isinstance(node, ast.FunctionDef)
            and node.name == "validate"
        ):
            spans.append((node.lineno, node.end_lineno))
    assert len(spans) == 3
    lines = source.splitlines()
    begin = min(start for start, _ in spans)
    end = max(finish for _, finish in spans)
    return "\n".join(lines[begin - 1 : end]) + "\n"


def _mutant_reference(name):
    old, new = {**REFERENCE_EDITS, **EQUIVALENT_EDITS}[name]
    source = _reference_block()
    assert old in source, name
    namespace = dict(vars(_REF))
    exec(compile(source.replace(old, new), f"<mutant {name}>", "exec"), namespace)  # noqa: S102
    return {key: namespace[key] for key in ("Refusal", "validate", "Ledger")}


def _fixture_red():
    """Labels of executed fixture checks that disagree with the reference
    currently bound; empty when green. Every check runs validate/publish on
    pinned or derived rows: no source-text or table-shape check counts."""
    red = []
    for section in ("happy", "boundary"):
        for row in CASES[section]:
            try:
                _run_accepted(row["event"])
            except BaseException:  # noqa: BLE001
                red.append(f"{section}:{row['name']}")
    for name in _malformed_names():
        for label, check in (
            (
                "",
                lambda name=name: test_malformed_row_refused_typed_without_echo_or_side_effect(
                    name
                ),
            ),
            ("repair", lambda name=name: test_malformed_minimal_repair_executes(name)),
        ):
            try:
                check()
            except BaseException:  # noqa: BLE001
                red.append(f"malformed:{name}{':' + label if label else ''}")
    for name in _rollback_names():
        try:
            test_rollback_row(name)
        except BaseException:  # noqa: BLE001
            red.append(f"rollback:{name}")
    for label, event in _HOSTILE_PROBES:
        try:
            for variant_label, hostile, failure_class in _event_variants(copy.deepcopy(event)):
                _hostile_event(event, variant_label, hostile, failure_class)
            for batch_label, batch in _batch_variants(copy.deepcopy(event)):
                _hostile_batch(batch_label, batch)
        except BaseException:  # noqa: BLE001
            red.append(f"hostile:{label}")
    return red


# two probes stand in for the full hostile set inside the mutant battery: one
# succeeded row and one failed row (which adds the error_code boundary)
_HOSTILE_PROBES = [
    next(pair for pair in _ACCEPTED if pair[1]["outcome"] == "succeeded"),
    next(pair for pair in _ACCEPTED if pair[1]["outcome"] == "failed"),
]


def test_reference_edits_apply():
    for name in {**REFERENCE_EDITS, **EQUIVALENT_EDITS}:
        _mutant_reference(name)


def test_reference_is_green():
    assert _fixture_red() == []


@pytest.mark.parametrize("name", sorted(REFERENCE_EDITS))
def test_reference_mutants_turn_the_fixture_red(name, monkeypatch):
    for key, value in _mutant_reference(name).items():
        monkeypatch.setattr(_REF, key, value)
    assert _fixture_red() != [], name


@pytest.mark.parametrize("name", sorted(EQUIVALENT_EDITS))
def test_equivalent_edits_keep_the_fixture_green(name, monkeypatch):
    for key, value in _mutant_reference(name).items():
        monkeypatch.setattr(_REF, key, value)
    assert _fixture_red() == [], name
